// ─── MEDULA Learn Engine — global subject taxonomy ──────────────────────────
// Single canonical taxonomy of the MBBS-level medical curriculum, consumed by
// the Learn UI, the medical map and the content packs. Rules:
//   · The 19 subject ids already seeded in the DB (prisma/seed-data.ts) are
//     FROZEN — id / code / name / year / color / blurb / neetWeight are kept
//     byte-identical; new optional fields (phase, systems, overlapsWith,
//     latinName, icon) are filled in additively.
//   · New subjects use new slug ids and never collide with DB ids.
//   · neetWeight values are editorial exam-relevance estimates (same nature as
//     the seeded ones); frontier subjects carry 0.
// Latin names follow the atlas-naming tradition already used by the branch
// galaxy (Morphologia, Physiologia, …) so every surface reads consistently.

import type { Phase, SubjectTaxonomy } from './types'

export const SUBJECT_TAXONOMY: SubjectTaxonomy[] = [
  // ── Pre-clinical — year 1 ────────────────────────────────────────────────
  {
    id: 'anatomy',
    code: 'ANAT',
    name: 'Anatomy',
    latinName: 'Morphologia',
    phase: 'pre-clinical',
    year: 1,
    color: '#38bdf8',
    blurb: 'The structural language of medicine — every clinical sign is anatomy in action.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'reproductive', 'nervous', 'musculoskeletal', 'endocrine', 'integumentary',
      'head-neck-special-senses',
    ],
    overlapsWith: ['histology', 'embryology', 'rad', 'surgery'],
    neetWeight: 4,
    icon: 'Bone',
  },
  {
    id: 'physiology',
    code: 'PHYS',
    name: 'Physiology',
    latinName: 'Physiologia',
    phase: 'pre-clinical',
    year: 1,
    color: '#22d3ee',
    blurb: 'How the body works. Every drug you will prescribe is physiology repeated.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'reproductive', 'nervous', 'musculoskeletal', 'endocrine', 'haematology',
      'immune-infection', 'integumentary',
    ],
    overlapsWith: ['biochemistry', 'pharmacology', 'medicine'],
    neetWeight: 8,
    icon: 'Activity',
  },
  {
    id: 'biochemistry',
    code: 'BIOCH',
    name: 'Biochemistry',
    latinName: 'Biochemia',
    phase: 'pre-clinical',
    year: 1,
    color: '#34d399',
    blurb: 'Molecular machinery — enzymes, pathways and their clinical fingerprints.',
    systems: ['haematology', 'hepatic', 'endocrine', 'renal', 'multisystem'],
    overlapsWith: ['physiology', 'genetics', 'medicine'],
    neetWeight: 8,
    icon: 'Atom',
  },
  {
    id: 'histology',
    code: 'HIST',
    name: 'Histology',
    latinName: 'Histologia',
    phase: 'pre-clinical',
    year: 1,
    color: '#a3e635',
    blurb: 'Microscopic anatomy — the tissue level where structure meets function and where pathology begins.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'reproductive', 'nervous', 'endocrine', 'integumentary', 'haematology',
      'immune-infection',
    ],
    overlapsWith: ['anatomy', 'physiology', 'pathology'],
    neetWeight: 2,
    icon: 'Microscope',
  },
  {
    id: 'embryology',
    code: 'EMB',
    name: 'Embryology',
    latinName: 'Embryologia',
    phase: 'pre-clinical',
    year: 1,
    color: '#fb7185',
    blurb: 'How one cell becomes a body — congenital anatomy explained by developmental logic.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'renal', 'reproductive',
      'nervous', 'musculoskeletal', 'head-neck-special-senses',
    ],
    overlapsWith: ['anatomy', 'genetics', 'obgy'],
    neetWeight: 2,
    icon: 'Sprout',
  },
  {
    id: 'genetics',
    code: 'GEN',
    name: 'Genetics',
    latinName: 'Genetica',
    phase: 'pre-clinical',
    year: 1,
    color: '#f0abfc',
    blurb: 'The molecular basis of inheritance and disease — from chromosomes to counselling.',
    systems: ['multisystem', 'haematology', 'nervous', 'endocrine'],
    overlapsWith: ['biochemistry', 'embryology', 'medicine'],
    neetWeight: 2,
    icon: 'Dna',
  },
  {
    id: 'immunology',
    code: 'IMM',
    name: 'Immunology',
    latinName: 'Immunologia',
    phase: 'pre-clinical',
    year: 1,
    color: '#5eead4',
    blurb: 'The body\u2019s defence logic — immunity, hypersensitivity, and the science behind vaccines.',
    systems: ['immune-infection', 'haematology', 'multisystem'],
    overlapsWith: ['microbiology', 'pathology', 'medicine'],
    neetWeight: 3,
    icon: 'ShieldCheck',
  },

  // ── Para-clinical — year 2 ───────────────────────────────────────────────
  {
    id: 'pathology',
    code: 'PATHO',
    name: 'Pathology',
    latinName: 'Pathologia',
    phase: 'para-clinical',
    year: 2,
    color: '#f472b6',
    blurb: 'The bridge from normal to diseased. Highest-yield para-clinical subject.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'reproductive', 'nervous', 'musculoskeletal', 'endocrine', 'integumentary',
      'haematology', 'immune-infection', 'head-neck-special-senses', 'multisystem',
    ],
    overlapsWith: ['medicine', 'microbiology', 'immunology', 'surgery'],
    neetWeight: 13,
    icon: 'FlaskConical',
  },
  {
    id: 'pharmacology',
    code: 'PHARM',
    name: 'Pharmacology',
    latinName: 'Pharmacologia',
    phase: 'para-clinical',
    year: 2,
    color: '#a78bfa',
    blurb: 'Drugs are applied physiology — mechanisms, indications, and traps.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'renal', 'nervous',
      'endocrine', 'reproductive', 'haematology', 'immune-infection',
      'musculoskeletal', 'multisystem',
    ],
    overlapsWith: ['physiology', 'medicine', 'microbiology'],
    neetWeight: 11,
    icon: 'Pill',
  },
  {
    id: 'microbiology',
    code: 'MICRO',
    name: 'Microbiology',
    latinName: 'Microbiologia',
    phase: 'para-clinical',
    year: 2,
    color: '#fbbf24',
    blurb: 'Infectious agents, lab diagnosis and the logic of antimicrobials.',
    systems: [
      'immune-infection', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'nervous', 'integumentary', 'reproductive', 'head-neck-special-senses',
      'multisystem',
    ],
    overlapsWith: ['immunology', 'medicine', 'cm'],
    neetWeight: 8,
    icon: 'Bug',
  },
  {
    id: 'fmt',
    code: 'FMT',
    name: 'Forensic Medicine & Toxicology',
    latinName: 'Medicina Forensis',
    phase: 'para-clinical',
    year: 2,
    color: '#94a3b8',
    blurb: 'Medicine meets law — injuries, poisoning, and legal procedure.',
    systems: ['multisystem', 'integumentary', 'nervous'],
    overlapsWith: ['cm', 'medicine', 'surgery'],
    neetWeight: 5,
    icon: 'Scale',
  },
  {
    id: 'cm',
    code: 'CM',
    name: 'Community Medicine',
    latinName: 'Medicina Communitatis',
    phase: 'para-clinical',
    year: 2,
    color: '#4ade80',
    blurb: 'Populations as patients — epidemiology, vaccines, and national programs.',
    systems: ['multisystem', 'immune-infection', 'reproductive'],
    overlapsWith: ['fmt', 'medicine', 'family-medicine'],
    neetWeight: 12,
    icon: 'Users',
  },

  // ── Clinical — years 3–4 ─────────────────────────────────────────────────
  {
    id: 'medicine',
    code: 'MED',
    name: 'General Medicine',
    latinName: 'Medicina Interna',
    phase: 'clinical',
    year: 3,
    color: '#60a5fa',
    blurb: 'The highest-weighted clinical subject — internal medicine mastery.',
    systems: [
      'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic', 'renal',
      'endocrine', 'nervous', 'haematology', 'immune-infection', 'musculoskeletal',
      'multisystem',
    ],
    overlapsWith: ['surgery', 'pharmacology', 'pathology', 'geriatrics'],
    neetWeight: 18,
    icon: 'Stethoscope',
  },
  {
    id: 'surgery',
    code: 'SURG',
    name: 'General Surgery',
    latinName: 'Chirurgia',
    phase: 'clinical',
    year: 3,
    color: '#f87171',
    blurb: 'Surgical principles, trauma, and high-yield operative logic.',
    systems: [
      'gastrointestinal', 'hepatic', 'cardiovascular', 'respiratory', 'endocrine',
      'integumentary', 'head-neck-special-senses', 'renal', 'multisystem',
    ],
    overlapsWith: ['medicine', 'orth', 'anes', 'rad'],
    neetWeight: 15,
    icon: 'Scissors',
  },
  {
    id: 'obgy',
    code: 'OBGY',
    name: 'Obstetrics & Gynaecology',
    latinName: 'Obstetria et Gynaecologia',
    phase: 'clinical',
    year: 4,
    color: '#e879f9',
    blurb: 'Two subjects, one specialty — pregnancy, labour, and female health.',
    systems: ['reproductive', 'endocrine', 'multisystem'],
    overlapsWith: ['surgery', 'peds', 'medicine'],
    neetWeight: 12,
    icon: 'HeartPulse',
  },
  {
    id: 'peds',
    code: 'PEDS',
    name: 'Paediatrics',
    latinName: 'Paediatricia',
    phase: 'clinical',
    year: 4,
    color: '#facc15',
    blurb: 'Children are not small adults — milestones, nutrition, and syndromes.',
    systems: [
      'multisystem', 'cardiovascular', 'respiratory', 'gastrointestinal', 'nervous',
      'haematology', 'immune-infection', 'musculoskeletal', 'renal',
    ],
    overlapsWith: ['obgy', 'medicine', 'surgery'],
    neetWeight: 8,
    icon: 'Baby',
  },
  {
    id: 'orth',
    code: 'ORTH',
    name: 'Orthopaedics',
    latinName: 'Orthopaedia',
    phase: 'clinical',
    year: 4,
    color: '#c084fc',
    blurb: 'Bones, joints, nerves — fractures and their complications.',
    systems: ['musculoskeletal', 'nervous', 'multisystem'],
    overlapsWith: ['surgery', 'physical-medicine-rehabilitation', 'rad'],
    neetWeight: 4,
    icon: 'Hand',
  },
  {
    id: 'ent',
    code: 'ENT',
    name: 'Otorhinolaryngology',
    latinName: 'Otorhinolaryngologia',
    phase: 'clinical',
    year: 3,
    color: '#fb923c',
    blurb: 'Head-neck anatomy applied — hearing, airway, and cancers.',
    systems: ['head-neck-special-senses', 'respiratory', 'nervous'],
    overlapsWith: ['surgery', 'opht'],
    neetWeight: 5,
    icon: 'Ear',
  },
  {
    id: 'opht',
    code: 'OPHT',
    name: 'Ophthalmology',
    latinName: 'Ophthalmologia',
    phase: 'clinical',
    year: 3,
    color: '#2dd4bf',
    blurb: 'The eye as a window — to hypertension, diabetes and neurology.',
    systems: ['head-neck-special-senses', 'nervous', 'endocrine', 'cardiovascular'],
    overlapsWith: ['ent', 'medicine'],
    neetWeight: 5,
    icon: 'Eye',
  },
  {
    id: 'psy',
    code: 'PSY',
    name: 'Psychiatry',
    latinName: 'Psychiatria',
    phase: 'clinical',
    year: 4,
    color: '#818cf8',
    blurb: 'Disorders of mind and behaviour — diagnosis and psychopharmacology.',
    systems: ['nervous', 'multisystem'],
    overlapsWith: ['medicine', 'cm'],
    neetWeight: 4,
    icon: 'Brain',
  },
  {
    id: 'derm',
    code: 'DERM',
    name: 'Dermatology',
    latinName: 'Dermatologia',
    phase: 'clinical',
    year: 4,
    color: '#fca5a5',
    blurb: 'Diagnosis by sight — morphology first, therapy second.',
    systems: ['integumentary', 'immune-infection', 'multisystem'],
    overlapsWith: ['medicine', 'immunology'],
    neetWeight: 3,
    icon: 'Layers',
  },
  {
    id: 'rad',
    code: 'RAD',
    name: 'Radiology',
    latinName: 'Radiologia',
    phase: 'clinical',
    year: 4,
    color: '#7dd3fc',
    blurb: 'Seeing the invisible — imaging patterns across all systems.',
    systems: [
      'multisystem', 'cardiovascular', 'respiratory', 'gastrointestinal', 'hepatic',
      'renal', 'nervous', 'musculoskeletal', 'head-neck-special-senses',
    ],
    overlapsWith: ['medicine', 'surgery', 'orth'],
    neetWeight: 3,
    icon: 'Scan',
  },
  {
    id: 'anes',
    code: 'ANES',
    name: 'Anaesthesia',
    latinName: 'Anaesthesiologia',
    phase: 'clinical',
    year: 4,
    color: '#9ca3af',
    blurb: 'Airway, breathing, circulation — physiology under stress.',
    systems: ['respiratory', 'cardiovascular', 'nervous', 'multisystem'],
    overlapsWith: ['critical-care', 'emergency-medicine', 'surgery'],
    neetWeight: 2,
    icon: 'Wind',
  },
  {
    id: 'emergency-medicine',
    code: 'EM',
    name: 'Emergency Medicine',
    latinName: 'Medicina Urgens',
    phase: 'clinical',
    year: 4,
    color: '#f43f5e',
    blurb: 'The first hours decide outcomes — recognition, resuscitation and referral.',
    systems: ['multisystem', 'cardiovascular', 'respiratory', 'nervous', 'musculoskeletal'],
    overlapsWith: ['anes', 'critical-care', 'surgery', 'medicine'],
    neetWeight: 2,
    icon: 'Siren',
  },
  {
    id: 'critical-care',
    code: 'CC',
    name: 'Critical Care Medicine',
    latinName: 'Cura Critica',
    phase: 'clinical',
    year: 4,
    color: '#dc2626',
    blurb: 'Physiology under artificial support — airway, ventilation, perfusion and sepsis.',
    systems: ['multisystem', 'respiratory', 'cardiovascular', 'renal', 'nervous', 'immune-infection'],
    overlapsWith: ['anes', 'emergency-medicine', 'medicine'],
    neetWeight: 2,
    icon: 'MonitorDot',
  },
  {
    id: 'oncology',
    code: 'ONCO',
    name: 'Oncology',
    latinName: 'Oncologia',
    phase: 'clinical',
    year: 4,
    color: '#7c3aed',
    blurb: 'Cancer biology and its systemic treatment — principles that tie pathology to therapy.',
    systems: ['multisystem', 'haematology', 'gastrointestinal', 'reproductive'],
    overlapsWith: ['medicine', 'surgery', 'palliative-medicine'],
    neetWeight: 3,
    icon: 'Radiation',
  },
  {
    id: 'family-medicine',
    code: 'FM',
    name: 'Family Medicine',
    latinName: 'Medicina Familiaris',
    phase: 'clinical',
    year: 3,
    color: '#84cc16',
    blurb: 'Continuity of care across ages — the longitudinal discipline that sees whole lives.',
    systems: ['multisystem', 'cardiovascular', 'endocrine', 'integumentary', 'immune-infection'],
    overlapsWith: ['cm', 'medicine', 'geriatrics'],
    neetWeight: 2,
    icon: 'Home',
  },
  {
    id: 'geriatrics',
    code: 'GERI',
    name: 'Geriatrics',
    latinName: 'Medicina Geriatrica',
    phase: 'clinical',
    year: 4,
    color: '#f59e0b',
    blurb: 'Medicine of the ageing — frailty, multimorbidity and function over diagnosis.',
    systems: ['multisystem', 'nervous', 'musculoskeletal', 'cardiovascular'],
    overlapsWith: ['medicine', 'family-medicine', 'palliative-medicine'],
    neetWeight: 1,
    icon: 'PersonStanding',
  },
  {
    id: 'physical-medicine-rehabilitation',
    code: 'PMR',
    name: 'Physical Medicine & Rehabilitation',
    latinName: 'Physiatria',
    phase: 'clinical',
    year: 4,
    color: '#0d9488',
    blurb: 'Restoring function after injury and disability — the science of rehabilitation.',
    systems: ['musculoskeletal', 'nervous', 'multisystem'],
    overlapsWith: ['orth', 'medicine', 'geriatrics'],
    neetWeight: 1,
    icon: 'Accessibility',
  },
  {
    id: 'palliative-medicine',
    code: 'PALL',
    name: 'Palliative Medicine',
    latinName: 'Medicina Palliativa',
    phase: 'clinical',
    year: 4,
    color: '#f9a8d4',
    blurb: 'Comfort as a clinical discipline — symptom control and end-of-life care.',
    systems: ['multisystem', 'nervous'],
    overlapsWith: ['oncology', 'family-medicine', 'geriatrics'],
    neetWeight: 1,
    icon: 'Sunset',
  },

  // ── Frontier ─────────────────────────────────────────────────────────────
  {
    id: 'ai-medicine',
    code: 'AIM',
    name: 'AI in Medicine',
    latinName: 'Medicina Artificialis',
    phase: 'frontier',
    year: 0, // not year-bound — spans the whole arc
    color: '#a855f7',
    blurb: 'Where computation meets care — models, data and decision support in clinical practice.',
    systems: ['frontier-ai', 'multisystem'],
    overlapsWith: ['rad', 'pathology', 'medicine'],
    neetWeight: 0, // frontier subject — outside the current exam blueprint
    icon: 'BrainCircuit',
  },
]

// ── Phases ──────────────────────────────────────────────────────────────────

export const PHASES: { phase: Phase; label: string; description: string }[] = [
  {
    phase: 'pre-clinical',
    label: 'Pre-clinical',
    description:
      'The foundations — structure, function and molecules of the normal body. Every later subject is rooted here.',
  },
  {
    phase: 'para-clinical',
    label: 'Para-clinical',
    description:
      'The bridge — disease mechanisms, drugs, microbes, law and populations that turn basic science into clinical reasoning.',
  },
  {
    phase: 'clinical',
    label: 'Clinical',
    description:
      'The wards — disciplines where knowledge becomes diagnosis, judgement and management at the bedside.',
  },
  {
    phase: 'specialized',
    label: 'Specialized',
    description:
      'Reserved for future sub-specialty tracks. Deliberately unpopulated for now — the phase exists so packs can extend the taxonomy without a schema change.',
  },
  {
    phase: 'frontier',
    label: 'Frontier',
    description:
      'Where medicine meets what is emerging — artificial intelligence, data and computation in clinical practice.',
  },
]

// ── Organ systems (the explorer axis) ───────────────────────────────────────
// Canonical keys. Topics declare their system by key; subjects list the keys
// they contribute to. Two display-only groups (multisystem, frontier-ai)
// collect cross-cutting content.

export const SYSTEMS: { system: string; label: string; emoji: string }[] = [
  { system: 'cardiovascular', label: 'Cardiovascular', emoji: '🫀' },
  { system: 'respiratory', label: 'Respiratory', emoji: '🫁' },
  { system: 'renal', label: 'Renal', emoji: '🫘' },
  { system: 'gastrointestinal', label: 'Gastrointestinal', emoji: '🍽️' },
  { system: 'hepatic', label: 'Hepatic', emoji: '🫗' },
  { system: 'endocrine', label: 'Endocrine', emoji: '⚖️' },
  { system: 'reproductive', label: 'Reproductive', emoji: '🤰' },
  { system: 'nervous', label: 'Nervous', emoji: '🧠' },
  { system: 'musculoskeletal', label: 'Musculoskeletal', emoji: '🦴' },
  { system: 'integumentary', label: 'Integumentary', emoji: '🧴' },
  { system: 'haematology', label: 'Haematology', emoji: '🩸' },
  { system: 'immune-infection', label: 'Immune & Infection', emoji: '🦠' },
  { system: 'head-neck-special-senses', label: 'Head, Neck & Special Senses', emoji: '👁️' },
  { system: 'multisystem', label: 'Multisystem', emoji: '🌐' },
  { system: 'frontier-ai', label: 'Frontier AI', emoji: '🤖' },
]
