// ─── MEDOS QUESTION BANK / FLASHCARDS / CONFUSION PAIRS ───
// All questions are original educational content written for this platform.

export interface SeedQuestion {
  id: string; stem: string; options: string[]; answer: number; explanation: string; teaching: string;
  subjectCode: string; system?: string; conceptId?: string; difficulty?: number; qtype?: string; tags?: string[]
}
export interface SeedFlashcard { id: string; front: string; back: string; subjectCode: string; system?: string; conceptId?: string; tags?: string[] }
export interface SeedConfusion { id: string; a: string; b: string; aCode?: string; bCode?: string; aPoints: string[]; bPoints: string[]; mnemonic?: string; subjectCode: string; system?: string }

export const questions: SeedQuestion[] = [
  // ── RENAL / NEPHRO (flagship) ──
  {
    id: 'q-nepho1', subjectCode: 'PATHO', system: 'renal', conceptId: 'c-nephrotic', difficulty: 1, qtype: 'vignette',
    stem: 'A 6-year-old boy presents with periorbital swelling for 1 week. Urine protein is 4+, with no dysmorphic RBCs or casts. Serum albumin is 1.8 g/dL. What is the most likely diagnosis?',
    options: ['Post-streptococcal glomerulonephritis', 'Minimal change disease', 'IgA nephropathy', 'Membranous nephropathy'],
    answer: 1,
    explanation: 'A young child with heavy proteinuria (4+), hypoalbuminemia and a bland urinary sediment (no RBC casts) has nephrotic syndrome. In children aged 2–12, the most common cause is minimal change disease — classically steroid-responsive. Nephritic features (hematuria, hypertension, RBC casts) point instead to post-infectious GN or IgA nephropathy.',
    teaching: 'Child + heavy proteinuria + bland urine = MCD until proven otherwise.',
  },
  {
    id: 'q-nepho2', subjectCode: 'PATHO', system: 'renal', conceptId: 'c-nephrotic', difficulty: 2, qtype: 'sba',
    stem: 'A patient with nephrotic syndrome develops left flank pain and worsening proteinuria. Doppler shows absence of renal venous flow. The hypercoagulability is best explained by loss of which substance in urine?',
    options: ['Immunoglobulin G', 'Antithrombin III', 'Complement C3', 'Transferrin'],
    answer: 1,
    explanation: 'Nephrotic syndrome causes urinary loss of antithrombin III (along with loss of proteins C/S and increased fibrinogen), producing a hypercoagulable state. Renal vein thrombosis is a classic complication — presenting with flank pain, hematuria and worsening proteinuria.',
    teaching: 'Loss of antithrombin III → renal vein thrombosis in nephrotic syndrome.',
  },
  {
    id: 'q-nephri1', subjectCode: 'PATHO', system: 'renal', conceptId: 'c-nephritic', difficulty: 2, qtype: 'vignette',
    stem: 'A 10-year-old develops cola-colored urine, periorbital edema and hypertension 2 weeks after a sore throat. C3 is low. Light microscopy will most likely show:',
    options: ['Podocyte foot process effacement only', 'Subepithelial "humps" with hypercellular glomeruli', 'Linear IgG along the GBM', 'Crescents in >50% of glomeruli'],
    answer: 1,
    explanation: 'Post-streptococcal glomerulonephritis is an immune-complex nephritic syndrome: hematuria with RBC casts, hypertension, low C3, 1–3 weeks after infection. Light microscopy shows hypercellular glomeruli; electron microscopy shows subepithelial humps ("lumpy-bumpy"). Linear IgG suggests anti-GBM disease; crescents suggest RPGN; foot process effacement alone is minimal change disease.',
    teaching: 'Post-strep GN = subepithelial humps + low C3.',
  },
  {
    id: 'q-nephri2', subjectCode: 'PATHO', system: 'renal', conceptId: 'c-nephritic', difficulty: 3, qtype: 'sba',
    stem: 'A 24-year-old with hemoptysis and rapidly progressive glomerulonephritis has linear IgG staining on renal biopsy. The underlying antibody targets:',
    options: ['Phospholipase A2 receptor', 'Alpha-3 chain of type IV collagen', 'Myeloperoxidase (MPO-ANCA)', 'Proteinase 3 (PR3-ANCA)'],
    answer: 1,
    explanation: 'Goodpasture syndrome (anti-GBM disease) produces pulmonary hemorrhage + RPGN. The antibody is directed against the α3 chain of type IV collagen, giving smooth LINEAR IgG deposition on immunofluorescence. PLA2R is associated with membranous nephropathy (granular), while MPO/PR3-ANCA are pauci-immune RPGN.',
    teaching: 'Linear IF = anti-GBM; granular = immune complex; none = ANCA.',
  },
  {
    id: 'q-aki1', subjectCode: 'MED', system: 'renal', conceptId: 'c-aki', difficulty: 2, qtype: 'vignette',
    stem: 'A 60-year-old on NSAIDs for arthritis develops oliguria after starting ramipril. Urine Na is 8 mmol/L, FENa 0.4%, BUN:Cr 28:1. The most likely mechanism is:',
    options: ['Acute tubular necrosis', 'Postrenal obstruction', 'Prerenal azotemia from disrupted prostaglandin–angiotensin balance', 'Acute interstitial nephritis'],
    answer: 2,
    explanation: 'NSAIDs inhibit prostaglandin-mediated afferent arteriolar dilation while ACE inhibitors block angiotensin-II–mediated efferent constriction — the "double hit" leaves glomerular pressure unable to compensate, producing functional (prerenal) AKI. Preserved concentrating ability (high BUN:Cr, low FENa) supports prerenal physiology over ATN (FENa >2%, muddy brown casts).',
    teaching: 'NSAID + ACEi = afferent + efferent block = prerenal AKI.',
  },
  {
    id: 'q-hyperk1', subjectCode: 'MED', system: 'renal', conceptId: 'c-hyperk', difficulty: 2, qtype: 'vignette',
    stem: 'A CKD patient presents with K⁺ 7.2 mEq/L, peaked T waves and widening QRS. After IV calcium gluconate, the next most appropriate step is:',
    options: ['Oral potassium binder alone', 'IV insulin with dextrose', 'Sodium bicarbonate', 'Immediate hemodialysis'],
    answer: 1,
    explanation: 'Management follows stabilize → shift → remove. Calcium stabilizes the myocardium but does not lower K⁺. The next step is shifting potassium intracellularly with IV regular insulin + dextrose (and/or nebulized salbutamol). Bicarbonate works mainly in acidotic patients; dialysis is reserved for refractory cases or those with severe renal failure.',
    teaching: 'Stabilize (Ca) → Shift (insulin+glucose) → Remove (binder/dialysis).',
  },
  // ── CARDIO ──
  {
    id: 'q-ecg1', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-ecg', difficulty: 1, qtype: 'vignette',
    stem: 'A 55-year-old man with crushing chest pain has ST elevation in leads II, III and aVF with ST depression in I and aVL. The occluded artery is most likely:',
    options: ['Left anterior descending', 'Left circumflex', 'Right coronary artery', 'Left main'],
    answer: 2,
    explanation: 'ST elevation in II, III, aVF localizes to the inferior wall, supplied by the right coronary artery in ~85% (right-dominant circulation). ST depression in I/aVL is reciprocal change. LAD gives anteroseptal changes (V1–V4); LCx gives lateral (I, aVL, V5–V6). Inferior MIs carry risk of AV block and RV involvement.',
    teaching: 'II, III, aVF = inferior = RCA (watch for bradycardia/RV infarct).',
  },
  {
    id: 'q-mi1', subjectCode: 'BIOCH', system: 'cardiovascular', conceptId: 'c-troponin', difficulty: 2, qtype: 'sba',
    stem: 'A patient with STEMI develops recurrent chest pain on day 3 post-MI. Which biomarker is most useful to diagnose reinfarction?',
    options: ['Troponin I', 'CK-MB', 'LDH', 'Myoglobin'],
    answer: 1,
    explanation: 'Troponin remains elevated for 7–14 days, masking a second rise. CK-MB normalizes by 48–72 hours, so a fresh CK-MB rise reliably indicates reinfarction. Myoglobin rises earliest but is nonspecific; LDH is obsolete.',
    teaching: 'Reinfarction question → CK-MB (troponin still up from first event).',
  },
  {
    id: 'q-bb1', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-betablock', difficulty: 1, qtype: 'sba',
    stem: 'A 50-year-old asthmatic with hypertension needs a beta-blocker. The safest choice is:',
    options: ['Propranolol', 'Metoprolol', 'Nadolol', 'Timolol'],
    answer: 1,
    explanation: 'β1-selective (cardioselective) blockers — metoprolol, atenolol, bisoprolol, nebivolol — spare β2 receptors in bronchi, making them relatively safer in asthma (still with caution). Propranolol, nadolol and timolol are non-selective and can precipitate severe bronchospasm.',
    teaching: 'Asthma → cardioselective only (metoprolol, atenolol, bisoprolol).',
  },
  {
    id: 'q-bb2', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-betablock', difficulty: 3, qtype: 'vignette',
    stem: 'A patient on chronic propranolol for migraine stops the drug abruptly and presents 3 days later with palpitations and rest angina. The mechanism is:',
    options: ['Rebound receptor upregulation', 'Coronary vasospasm from ergot withdrawal', 'Thyroid storm', 'Anxiety-related catecholamine surge'],
    answer: 0,
    explanation: 'Chronic β-blockade causes compensatory β-receptor upregulation. Abrupt withdrawal produces transient supersensitivity to catecholamines — rebound tachycardia, hypertension, angina and even MI. Beta-blockers should always be tapered over 1–2 weeks.',
    teaching: 'Never stop beta-blockers abruptly — taper to avoid rebound.',
  },
  {
    id: 'q-acei1', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-acei', difficulty: 2, qtype: 'sba',
    stem: 'The dry cough caused by ramipril is best explained by accumulation of:',
    options: ['Substance P', 'Bradykinin', 'Angiotensin I', 'Renin'],
    answer: 1,
    explanation: 'ACE also degrades bradykinin. Inhibiting ACE raises bradykinin levels → airway irritation (dry cough in 5–20%) and, rarely, life-threatening angioedema. Switching to an ARB (blocks AT1 without affecting bradykinin) resolves the cough.',
    teaching: 'ACEi cough/angioedema = bradykinin; switch to ARB.',
  },
  {
    id: 'q-cardcyc1', subjectCode: 'PHYS', system: 'cardiovascular', conceptId: 'c-cardcycle', difficulty: 2, qtype: 'sba',
    stem: 'The second heart sound (S2) coincides with which phase of the cardiac cycle?',
    options: ['Onset of atrial systole', 'Closure of AV valves at onset of ventricular systole', 'Closure of semilunar valves at onset of isovolumetric relaxation', 'Rapid ventricular filling'],
    answer: 2,
    explanation: 'S2 is produced by closure of the aortic and pulmonary (semilunar) valves at the end of ejection — marking the start of isovolumetric relaxation. S1 (AV valve closure) starts isovolumetric contraction. S3 occurs during rapid filling; S4 during atrial contraction against a stiff ventricle.',
    teaching: 'S1 starts systole; S2 starts isovolumetric relaxation.',
  },
  {
    id: 'q-cardcyc2', subjectCode: 'PHYS', system: 'cardiovascular', conceptId: 'c-cardcycle', difficulty: 2, qtype: 'sba',
    stem: 'An S3 gallop in a 45-year-old with dilated cardiomyopathy is produced during:',
    options: ['Atrial systole against a stiff ventricle', 'Isovolumetric contraction', 'Rapid passive ventricular filling', 'Ejection phase'],
    answer: 2,
    explanation: 'S3 occurs in early diastole during the rapid passive filling phase, when a volume-overloaded ventricle receives blood against a compliant but dilated wall. It reflects volume overload (dilated CMP, MR) — normal in children/athletes. S4 occurs in atrial contraction against a stiff (hypertrophied/ischemic) ventricle.',
    teaching: 'S3 = volume overload (rapid filling); S4 = stiff ventricle.',
  },
  {
    id: 'q-htn1', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-htn', difficulty: 2, qtype: 'vignette',
    stem: 'A 45-year-old with BP 150/95 has unprovoked hypokalemia (K 2.9) and mild metabolic alkalosis. The most appropriate next investigation is:',
    options: ['Renal artery Doppler', 'Plasma aldosterone-to-renin ratio', '24-hour urinary metanephrines', 'Overnight dexamethasone suppression test'],
    answer: 1,
    explanation: 'Hypertension with unprovoked hypokalemia and metabolic alkalosis suggests primary hyperaldosteronism (Conn syndrome) — now the most common cause of secondary hypertension. Screening test: plasma aldosterone-to-renin ratio (high aldosterone, suppressed renin). Renal artery stenosis, phaeochromocytoma and Cushing have different fingerprints.',
    teaching: 'HTN + hypokalemia = check aldosterone:renin ratio.',
  },
  {
    id: 'q-htn2', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-htn', difficulty: 1, qtype: 'sba',
    stem: 'Which antihypertensive class is absolutely contraindicated in pregnancy?',
    options: ['Labetalol', 'Methyldopa', 'ACE inhibitors', 'Extended-release nifedipine'],
    answer: 2,
    explanation: 'ACE inhibitors and ARBs cause fetal renal failure, oligohydramnios, and fetopathy — contraindicated throughout pregnancy. Safe options include labetalol (first-line), methyldopa (longest safety record) and nifedipine.',
    teaching: 'Pregnancy: labetalol/methyldopa/nifedipine OK; ACEi/ARB never.',
  },
  // ── ENDOCRINE ──
  {
    id: 'q-dka1', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-dka', difficulty: 2, qtype: 'vignette',
    stem: 'A 22-year-old with T1DM presents in DKA: glucose 480, pH 7.05, K 5.8. Insulin infusion is started. The potassium must be added to fluids once:',
    options: ['Immediately, regardless of levels', 'When glucose falls below 200 mg/dL', 'When serum K falls below 5.2–5.3 mEq/L and urine output is adequate', 'Only after bicarbonate is given'],
    answer: 2,
    explanation: 'Total-body potassium in DKA is depleted despite high serum levels (acidosis + insulin deficiency drive K⁺ out of cells). Insulin shifts K⁺ back intracellularly, so once serum K falls below ~5.2–5.3 with adequate urine output, potassium replacement must begin to avoid fatal hypokalemia. Bicarbonate is only for pH <6.9 and worsens hypokalemia.',
    teaching: 'Insulin drops K⁺ — replace once K <5.2 with good urine flow.',
  },
  {
    id: 'q-dm1', subjectCode: 'BIOCH', system: 'endocrine', conceptId: 'c-hba1c', difficulty: 1, qtype: 'sba',
    stem: 'HbA1c may be falsely LOW in which condition?',
    options: ['Iron deficiency anemia', 'Hemolytic anemia', 'Chronic kidney disease', 'Splenomegaly'],
    answer: 1,
    explanation: 'HbA1c reflects glycemia over the RBC lifespan (~120 days). Any state shortening RBC survival — hemolysis, recent transfusion, pregnancy, erythropoietin — falsely lowers HbA1c. Iron deficiency anemia and CKD falsely raise it.',
    teaching: 'Short RBC life → low HbA1c; iron deficiency/CKD → high.',
  },
  {
    id: 'q-dm2', subjectCode: 'PHARM', system: 'endocrine', conceptId: 'c-metformin', difficulty: 2, qtype: 'sba',
    stem: 'The primary mechanism of metformin is:',
    options: ['Stimulation of pancreatic β-cell insulin release', 'AMPK activation reducing hepatic gluconeogenesis', 'Blockade of SGLT2 in proximal tubule', 'GLP-1 receptor agonism'],
    answer: 1,
    explanation: 'Metformin activates AMP-activated protein kinase, suppressing hepatic gluconeogenesis and improving peripheral insulin sensitivity. It does not cause hypoglycemia as monotherapy and is weight-neutral. Sulfonylureas stimulate insulin release; SGLT2 blockers act in the kidney; GLP-1 agonists are injectable incretin mimetics.',
    teaching: 'Metformin = AMPK, liver, no hypoglycemia, weight neutral.',
  },
  {
    id: 'q-graves1', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-graves', difficulty: 2, qtype: 'vignette',
    stem: 'A 30-year-old woman has weight loss, heat intolerance, exophthalmos and diffuse goiter with a bruit. Her radioiodine uptake scan will show:',
    options: ['Diffuse increased uptake', 'Focal hot nodules with suppressed background', 'No uptake', 'Cold nodule'],
    answer: 0,
    explanation: 'Graves disease shows diffuse, increased radioiodine uptake because TSH-receptor stimulating antibodies drive every thyrocyte. Toxic multinodular goiter shows patchy hot nodules; thyroiditis and exogenous hormone intake show near-zero uptake (suppressed gland); a cold nodule raises malignancy concern.',
    teaching: 'Diffuse uptake = Graves; hot nodules = TMNG; no uptake = thyroiditis/factitious.',
  },
  {
    id: 'q-storm1', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-thyroidstorm', difficulty: 3, qtype: 'sba',
    stem: 'In managing thyroid storm, iodine must be administered at least 1 hour AFTER the thionamide because:',
    options: ['Iodine impairs thionamide absorption', 'Iodine is a substrate for new hormone synthesis and would fuel hormone production first', 'Iodine causes immediate hypotension', 'PTU requires iodine for activation'],
    answer: 1,
    explanation: 'Iodine is the substrate for thyroid hormone synthesis. Giving it before blocking synthesis (thionamide inhibits TPO) supplies fuel for new hormone production — worsening the storm. PTU first (also blocks peripheral T4→T3), then iodine exploits the Wolff-Chaikoff effect.',
    teaching: 'Block first (PTU), then flood (iodine) — never reverse.',
  },
  {
    id: 'q-cushing1', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-cushing', difficulty: 3, qtype: 'sba',
    stem: 'A patient with Cushingoid features has high ACTH that does NOT suppress with high-dose dexamethasone. The most likely source is:',
    options: ['Pituitary microadenoma', 'Adrenal adenoma', 'Ectopic ACTH secretion', 'Exogenous steroid use'],
    answer: 2,
    explanation: 'Ectopic ACTH (small cell lung cancer, carcinoid) is resistant to high-dose dexamethasone suppression. Pituitary adenomas (Cushing disease) typically suppress with high-dose dex. Adrenal adenoma has LOW ACTH; exogenous steroids suppress the whole axis.',
    teaching: 'High-dose dex: pituitary suppresses, ectopic does not.',
  },
  // ── RESPIRATORY ──
  {
    id: 'q-pft1', subjectCode: 'PHYS', system: 'respiratory', conceptId: 'c-spirometry', difficulty: 1, qtype: 'sba',
    stem: 'A 60-year-old smoker has FEV1 55% predicted, FVC 90% predicted, FEV1/FVC 0.52. The pattern is:',
    options: ['Restrictive', 'Obstructive', 'Normal', 'Mixed with predominance of restriction'],
    answer: 1,
    explanation: 'FEV1/FVC below 0.7 defines airflow obstruction — here with reduced FEV1 and relatively preserved FVC, consistent with COPD. In restriction, both FEV1 and FVC fall proportionately, keeping the ratio normal or raised.',
    teaching: 'Ratio <0.7 = obstruction; ratio preserved + low FVC = restriction.',
  },
  {
    id: 'q-asthma1', subjectCode: 'MED', system: 'respiratory', conceptId: 'c-asthma-copd', difficulty: 2, qtype: 'sba',
    stem: 'Which agent must NEVER be used as monotherapy in asthma?',
    options: ['Inhaled corticosteroid', 'Long-acting beta-agonist (salmeterol)', 'Leukotriene receptor antagonist', 'Ipratropium'],
    answer: 1,
    explanation: 'LABA monotherapy in asthma increases severe exacerbations and asthma-related deaths (SMART trial). LABAs must always be combined with an inhaled corticosteroid, which controls the underlying inflammation.',
    teaching: 'LABA without ICS in asthma = increased mortality.',
  },
  {
    id: 'q-tb1', subjectCode: 'MICRO', system: 'respiratory', conceptId: 'c-antitb', difficulty: 1, qtype: 'sba',
    stem: 'A patient on ATT develops difficulty distinguishing red and green traffic signals. The offending drug is:',
    options: ['Isoniazid', 'Rifampin', 'Pyrazinamide', 'Ethambutol'],
    answer: 3,
    explanation: 'Ethambutol causes retrobulbar optic neuritis — loss of red-green color discrimination and visual acuity, dose-dependent. Isoniazid causes peripheral neuropathy (prevent with B6) and hepatotoxicity; rifampin causes orange discoloration of secretions and enzyme induction; pyrazinamide causes hyperuricemia and hepatotoxicity.',
    teaching: 'Ethambutol = eyes; INH = nerves; rifampin = orange; PZA = urate.',
  },
  {
    id: 'q-tb2', subjectCode: 'MICRO', system: 'respiratory', conceptId: 'c-tb', difficulty: 2, qtype: 'sba',
    stem: 'The first-line test for pulmonary tuberculosis under NTEP that also detects rifampin resistance is:',
    options: ['Sputum Ziehl-Neelsen smear', 'CBNAAT (GeneXpert)', 'Mantoux test', 'Chest X-ray'],
    answer: 1,
    explanation: 'CBNAAT/GeneXpert MTB-RIF is the initial diagnostic test in NTEP — it detects M. tuberculosis DNA AND rifampin resistance within ~2 hours. Smear microscopy cannot detect resistance; Mantoux cannot distinguish infection from disease.',
    teaching: 'NTEP first test = CBNAAT (detects + resistance in 2 h).',
  },
  // ── HEMATOLOGY ──
  {
    id: 'q-ida1', subjectCode: 'PATHO', system: 'hematology', conceptId: 'c-idacda', difficulty: 1, qtype: 'sba',
    stem: 'A 40-year-old woman with chronic rheumatoid arthritis has microcytic anemia: ferritin 180 ng/mL, TIBC low, serum iron low. The diagnosis is:',
    options: ['Iron deficiency anemia', 'Anemia of chronic disease', 'Thalassemia trait', 'Sideroblastic anemia'],
    answer: 1,
    explanation: 'Anemia of chronic disease shows LOW serum iron with LOW/normal TIBC and NORMAL-to-HIGH ferritin (ferritin is an acute-phase reactant — it rises with inflammation, masking true iron status). Iron deficiency shows low ferritin with HIGH TIBC; thalassemia trait has normal iron studies with disproportionate microcytosis.',
    teaching: 'Inflammation raises ferritin — ACD: iron low, TIBC low, ferritin high.',
  },
  {
    id: 'q-aml1', subjectCode: 'PATHO', system: 'hematology', conceptId: 'c-leukemia', difficulty: 2, qtype: 'sba',
    stem: 'A 35-year-old with gum bleeding and pancytopenia has blasts with Auer rods. DIC is complicating the course. The treatment that targets the underlying biology is:',
    options: ['Imatinib', 'All-trans retinoic acid', 'Rituximab', 'Hydroxyurea'],
    answer: 1,
    explanation: 'Auer rods + DIC identify acute promyelocytic leukemia (AML-M3) with t(15;17) PML-RARA fusion. All-trans retinoic acid (ATRA) binds the fusion receptor and forces differentiation of blasts — a paradigm of targeted therapy with high cure rates. Imatinib targets BCR-ABL in CML.',
    teaching: 'Auer rods + DIC = APL = ATRA (differentiation therapy).',
  },
  // ── GI / MICRO ──
  {
    id: 'q-hpy1', subjectCode: 'MICRO', system: 'gastrointestinal', conceptId: 'c-hpylori', difficulty: 2, qtype: 'sba',
    stem: 'The best non-invasive test to CONFIRM eradication of H. pylori after therapy is:',
    options: ['Serum anti-H. pylori IgG', 'Urea breath test', 'Rapid urease test on biopsy', 'Serum pepsinogen'],
    answer: 1,
    explanation: 'The urea breath test (or stool antigen test) detects CURRENT infection and is ideal for confirming eradication ≥4 weeks after antibiotics (and 2 weeks off PPI). Serology detects antibodies that persist after cure — cannot distinguish past from active infection. Rapid urease test is invasive (endoscopic biopsy).',
    teaching: 'Eradication check: urea breath/stool antigen; serology never.',
  },
  {
    id: 'q-ulcer1', subjectCode: 'MED', system: 'gastrointestinal', conceptId: 'c-ulcer', difficulty: 1, qtype: 'vignette',
    stem: 'A 50-year-old has epigastric pain that WORSENS with eating, with 4 kg weight loss. Upper GI endoscopy shows an antral ulcer. The essential next step is:',
    options: ['Test for H. pylori and treat', 'Biopsy the ulcer margin', 'Start PPI trial for 8 weeks', 'CT abdomen'],
    answer: 1,
    explanation: 'Gastric ulcers — especially with alarm features (weight loss, worsening pain with food, age >40) — must be BIOPSIED to exclude malignancy (re-biopsy to confirm healing too). Duodenal ulcers are almost never malignant.',
    teaching: 'Gastric ulcer = biopsy; duodenal ulcer = H. pylori test.',
  },
  // ── CM / BIOSTATS ──
  {
    id: 'q-epi1', subjectCode: 'CM', conceptId: 'c-epidesign', difficulty: 2, qtype: 'sba',
    stem: 'In a study, 30 of 100 smokers and 10 of 100 non-smokers develop lung cancer over 10 years. The relative risk is:',
    options: ['3.0', '0.3', '2.4', 'Cannot be calculated'],
    answer: 0,
    explanation: 'Risk in exposed = 30/100 = 0.3; risk in unexposed = 10/100 = 0.1. RR = 0.3/0.1 = 3.0 — smokers have three times the risk. (Odds ratio would be (30×90)/(70×10) ≈ 3.86.) Cohort studies yield relative risk directly.',
    teaching: 'RR = risk(exposed)/risk(unexposed) — cohort studies.',
  },
  {
    id: 'q-epi2', subjectCode: 'CM', conceptId: 'c-epidesign', difficulty: 2, qtype: 'sba',
    stem: 'A screening test with sensitivity 90% and specificity 95% is applied to a population where prevalence rises from 1% to 10%. What happens to the positive predictive value?',
    options: ['Falls', 'Rises', 'Unchanged', 'Cannot be predicted'],
    answer: 1,
    explanation: 'PPV depends on prevalence: as disease prevalence increases, a positive result is more likely to be true, so PPV rises (sensitivity/specificity are properties of the test itself and do not change). This is why screening is most efficient in high-risk groups.',
    teaching: 'Higher prevalence → higher PPV (sens/spec fixed).',
  },
  {
    id: 'q-vac1', subjectCode: 'CM', conceptId: 'c-vaccines', difficulty: 2, qtype: 'sba',
    stem: 'Which of the following vaccines in India\'s Universal Immunisation Programme is a LIVE attenuated vaccine?',
    options: ['DPT', 'Hepatitis B', 'Measles-Rubella (MR)', 'Pentavalent'],
    answer: 2,
    explanation: 'MR/measles is live attenuated (as are BCG, OPV, JE SA-14-14-2, varicella). DPT, Hepatitis B, Hib, IPV and pentavalent components are killed/inactivated.',
    teaching: 'Live: BCG, OPV, MR, JE, varicella. Killed: DPT, HepB, IPV, Hib.',
  },
  // ── ANATOMY / SURGERY ──
  {
    id: 'q-fem1', subjectCode: 'ANAT', system: 'musculoskeletal', conceptId: 'c-femoral', difficulty: 1, qtype: 'sba',
    stem: 'In the femoral triangle, from lateral to medial, the structures are:',
    options: ['Vein, artery, nerve', 'Nerve, artery, vein', 'Artery, nerve, vein', 'Artery, vein, nerve'],
    answer: 1,
    explanation: 'NAVEL (lateral→medial): Nerve (femoral), Artery, Vein, Empty space/Lymphatics. The femoral nerve lies OUTSIDE the femoral sheath. Femoral hernia passes medial to the vein through the femoral canal.',
    teaching: 'NAVEL — nerve most lateral, vein most medial.',
  },
  {
    id: 'q-hern1', subjectCode: 'SURG', conceptId: 'c-hernia', difficulty: 2, qtype: 'sba',
    stem: 'An indirect inguinal hernia sac passes relative to the inferior epigastric vessels and the deep ring:',
    options: ['Medial to vessels, through Hesselbach triangle', 'Lateral to vessels, through the deep (internal) ring', 'Directly through the conjoint tendon', 'Through the femoral canal'],
    answer: 1,
    explanation: 'Indirect hernias enter the deep inguinal ring LATERAL to the inferior epigastric vessels and follow the cord (can reach the scrotum). Direct hernias push through Hesselbach triangle MEDIAL to the vessels. Femoral hernias pass below the inguinal ligament through the femoral canal.',
    teaching: 'Indirect = lateral to IE vessels via deep ring; direct = medial.',
  },
  // ── OBGY ──
  {
    id: 'q-preec1', subjectCode: 'OBGY', system: 'cardiovascular', conceptId: 'c-preec', difficulty: 2, qtype: 'vignette',
    stem: 'A 32-week pregnant woman with preeclampsia develops a generalized tonic-clonic seizure. Besides supportive care, the definitive drug and its antidote are:',
    options: ['Diazepam — flumazenil', 'Magnesium sulfate — calcium gluconate', 'Phenytoin — pyridoxine', 'Labetalol — atropine'],
    answer: 1,
    explanation: 'Eclampsia is treated with IV/IM magnesium sulfate (Pritchard regimen), which prevents and controls seizures via NMDA antagonism and cerebral vasodilation. Toxicity (loss of deep tendon reflexes → respiratory depression) is reversed with calcium gluconate — a classic antidote pair.',
    teaching: 'Eclampsia = MgSO4; toxicity reversed by calcium gluconate.',
  },
  {
    id: 'q-preec2', subjectCode: 'PHARM', conceptId: 'c-preec', difficulty: 2, qtype: 'sba',
    stem: 'Magnesium sulfate toxicity is monitored clinically by all EXCEPT:',
    options: ['Patellar (deep tendon) reflexes', 'Respiratory rate', 'Urine output', 'Pupillary size'],
    answer: 3,
    explanation: 'MgSO4 monitoring: knee jerk present, respiratory rate ≥12–16/min, urine output ≥25–30 mL/h (kidney excretes Mg). Reflexes disappear first (~7–10 mEq/L), then respiratory paralysis. Pupils are not part of the monitoring triad.',
    teaching: 'MgSO4 triad: reflexes, respiration, urine output.',
  },
  // ── OPHTHO ──
  {
    id: 'q-ret1', subjectCode: 'OPHT', system: 'endocrine', conceptId: 'c-diabretino', difficulty: 2, qtype: 'sba',
    stem: 'The earliest clinically detectable lesion of diabetic retinopathy is:',
    options: ['Cotton-wool spots', 'Microaneurysms', 'Neovascularization', 'Vitreous hemorrhage'],
    answer: 1,
    explanation: 'Microaneurysms — saccular outpouchings of capillary walls from pericyte loss — are the earliest ophthalmoscopically visible lesion. Cotton-wool spots (nerve fiber layer infarcts) come later in NPDR; neovascularization defines progression to PDR.',
    teaching: 'First visible: microaneurysms. Neovessels = PDR.',
  },
  // ── PHYSIOLOGY ──
  {
    id: 'q-raas1', subjectCode: 'PHYS', system: 'renal', conceptId: 'c-raas', difficulty: 2, qtype: 'sba',
    stem: 'Renin secretion from juxtaglomerular cells is stimulated by all EXCEPT:',
    options: ['Decreased renal perfusion pressure', 'Increased NaCl delivery to macula densa', 'Beta-1 adrenergic stimulation', 'Prostaglandins'],
    answer: 1,
    explanation: 'Renin rises with LOW perfusion, LOW NaCl at the macula densa (sensed as low filtered load) and β1 stimulation. Increased NaCl delivery INHIBITS renin (tubuloglomerular feedback). Prostaglandins (PGE2/PGI2) stimulate renin — hence NSAIDs suppress it.',
    teaching: 'Low pressure/NaCl/β1 → renin up. High NaCl → renin down.',
  },
  {
    id: 'q-gfr1', subjectCode: 'PHYS', system: 'renal', conceptId: 'c-gfr', difficulty: 2, qtype: 'vignette',
    stem: 'A patient with bilateral renal artery stenosis is started on an ACE inhibitor; creatinine rises 60% within a week. The mechanism is:',
    options: ['Allergic interstitial nephritis', 'Loss of efferent arteriolar tone maintaining filtration pressure', 'Cholesterol embolization', 'Volume overload'],
    answer: 1,
    explanation: 'In renal artery stenosis, glomerular filtration depends on angiotensin-II–mediated efferent constriction. ACE inhibition removes this → filtration pressure and GFR fall abruptly, raising creatinine. A rise >30–50% mandates stopping the drug and evaluating renovascular disease.',
    teaching: 'Bilateral RAS + ACEi = GFR collapse (efferent dependence).',
  },
  {
    id: 'q-insulin1', subjectCode: 'PHYS', system: 'endocrine', conceptId: 'c-insulin', difficulty: 1, qtype: 'sba',
    stem: 'Insulin promotes potassium entry into cells primarily by:',
    options: ['Opening potassium channels', 'Stimulating Na⁺/K⁺-ATPase', 'Increasing renal K⁺ excretion', 'Inhibiting aldosterone'],
    answer: 1,
    explanation: 'Insulin binding increases Na⁺/K⁺-ATPase activity (via signaling pathways), driving K⁺ intracellularly with Na⁺ — the basis of insulin-dextrose therapy for hyperkalemia. β2 agonists act similarly.',
    teaching: 'Insulin + glucose shift K⁺ in via Na/K-ATPase.',
  },
  {
    id: 'q-thy1', subjectCode: 'PHYS', system: 'endocrine', conceptId: 'c-thyroidphys', difficulty: 2, qtype: 'sba',
    stem: 'In pregnancy, total T4 rises but free T4 remains normal because:',
    options: ['hCG suppresses TSH permanently', 'Hepatic synthesis of TBG increases', 'Placental deiodinase destroys T4', 'Renal iodine loss falls'],
    answer: 1,
    explanation: 'Estrogen increases hepatic thyroxine-binding globulin (TBG), raising TOTAL T4 while FREE T4 (the active fraction) stays normal. Free hormone is what feedback loops and tissues sense.',
    teaching: 'Pregnancy: ↑TBG → total T4 up, free T4 normal.',
  },
  // ── RAPID-FIRE ──
  { id: 'q-r1', subjectCode: 'PHARM', system: 'renal', conceptId: 'c-diuretics', difficulty: 1, qtype: 'rapid', stem: 'Furosemide acts on which transporter?', options: ['NCC in DCT', 'NKCC2 in thick ascending limb', 'ENaC in collecting duct', 'Aquaporin-2'], answer: 1, explanation: 'Loop diuretics block the Na-K-2Cl (NKCC2) cotransporter in the thick ascending limb of Henle — the most powerful diuretic site.', teaching: 'Loop = NKCC2 = TAL.' },
  { id: 'q-r2', subjectCode: 'PHARM', system: 'renal', conceptId: 'c-diuretics', difficulty: 2, qtype: 'rapid', stem: 'Thiazides REDUCE urinary excretion of:', options: ['Calcium', 'Sodium', 'Potassium', 'Magnesium'], answer: 0, explanation: 'Thiazides enhance distal calcium reabsorption (contract hypovolemia-driven proximal reabsorption + DCT effects) — useful in recurrent calcium stones and osteoporosis. They waste Na, K, Mg, and Cl.', teaching: 'Thiazide: hypercalcemia-ic (keeps Ca), wastes K/Mg/Na.' },
  { id: 'q-r3', subjectCode: 'PHARM', conceptId: 'c-diuretics', difficulty: 1, qtype: 'rapid', stem: 'Spironolactone-induced gynecomastia is due to:', options: ['Estrogen agonism', 'Progesterone receptor block', 'Binding to androgen and progesterone receptors', 'Prolactin elevation'], answer: 2, explanation: 'Spironolactone binds androgen and progesterone receptors (antagonism) → gynecomastia, menstrual irregularity. Eplerenone is selective for mineralocorticoid receptors and avoids these effects.', teaching: 'Spironolactone: antiandrogen effects; eplerenone: selective.' },
  { id: 'q-r4', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-ami', difficulty: 1, qtype: 'rapid', stem: 'The goal door-to-balloon time for primary PCI is:', options: ['30 minutes', '60 minutes', '90 minutes', '180 minutes'], answer: 2, explanation: 'Primary PCI should be performed within 90 minutes of first medical contact (120 min if transfer needed); fibrinolysis door-to-needle target is 30 minutes.', teaching: 'PCI ≤90 min; lysis ≤30 min.' },
  { id: 'q-r5', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-ami', difficulty: 2, qtype: 'rapid', stem: 'A pansystolic murmur with precordial thrill and heart failure 5 days after STEMI suggests:', options: ['Papillary muscle rupture', 'Ventricular free wall rupture', 'Ventricular septal rupture', 'Pericarditis'], answer: 2, explanation: 'VSR (septal rupture) occurs 3–7 days post-MI: new harsh pansystolic murmur + palpable thrill + step-up in O2 saturation in RV. Free wall rupture causes tamponade and sudden death; papillary muscle rupture causes acute severe MR without a thrill.', teaching: 'Thrill + pansystolic post-MI = septal rupture.' },
  { id: 'q-r6', subjectCode: 'PHYS', system: 'respiratory', conceptId: 'c-spirometry', difficulty: 1, qtype: 'rapid', stem: 'DLCO is characteristically REDUCED in:', options: ['Asthma exacerbation', 'Emphysema', 'Obesity', 'Pulmonary hemorrhage'], answer: 1, explanation: 'Emphysema destroys alveolar-capillary surface → low DLCO. DLCO is normal/high in asthma (increased blood volume) and HIGH in pulmonary hemorrhage (Hb binds CO).', teaching: 'DLCO: ↓ emphysema/IPF; ↑ asthma/hemorrhage.' },
  { id: 'q-r7', subjectCode: 'MICRO', system: 'respiratory', conceptId: 'c-tb', difficulty: 1, qtype: 'rapid', stem: 'Rifampin characteristically turns body fluids:', options: ['Blue', 'Orange', 'Green', 'No change'], answer: 1, explanation: 'Rifampin colors urine, tears, sweat, and sputum orange-red — harmless but important for adherence counseling; also induces CYP450 (OCP failure, warfarin interactions).', teaching: 'Rifampin = orange secretions + enzyme inducer.' },
  { id: 'q-r8', subjectCode: 'PATHO', system: 'hematology', conceptId: 'c-idacda', difficulty: 1, qtype: 'rapid', stem: 'Mentzer index (MCV/RBC) <13 suggests:', options: ['Iron deficiency anemia', 'Thalassemia trait', 'Sideroblastic anemia', 'ACD'], answer: 1, explanation: 'Mentzer index <13 (microcytosis out of proportion to anemia) points to thalassemia trait; >13 to iron deficiency. Confirmation needs iron studies/hemoglobin electrophoresis.', teaching: 'Mentzer <13 = thal trait.' },
  { id: 'q-r9', subjectCode: 'PHYS', system: 'endocrine', conceptId: 'c-thyroidphys', difficulty: 1, qtype: 'rapid', stem: 'Propylthiouracil (unlike methimazole) additionally inhibits:', options: ['Iodide trapping', 'Peripheral T4→T3 conversion', 'TSH secretion', 'Thyroglobulin synthesis'], answer: 1, explanation: 'PTU blocks TPO (like methimazole) AND inhibits 5′-deiodinase, blocking T4→T3 conversion — preferred in thyroid storm and first trimester (methimazole teratogenic then, but PTU has hepatotoxicity risk after).', teaching: 'PTU = TPO + deiodinase; pregnancy 1st trimester/storm.' },
  { id: 'q-r10', subjectCode: 'MED', system: 'renal', conceptId: 'c-aki', difficulty: 1, qtype: 'rapid', stem: '"Muddy brown granular casts" in urine indicate:', options: ['Prerenal azotemia', 'Acute tubular necrosis', 'Acute interstitial nephritis', 'Glomerulonephritis'], answer: 1, explanation: 'Muddy brown casts = sloughed tubular epithelial cells = ATN. WBC casts (with eosinophils) = interstitial nephritis; RBC casts = glomerulonephritis; bland sediment = prerenal/nephrotic.', teaching: 'Muddy brown = ATN; RBC = GN; WBC = AIN.' },
  { id: 'q-r11', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-dka', difficulty: 1, qtype: 'rapid', stem: 'Bicarbonate in DKA is indicated only when pH is:', options: ['<7.3', '<7.1', '<6.9', 'Never indicated'], answer: 2, explanation: 'Guidelines reserve bicarbonate for pH <6.9 (severe acidosis) as it risks hypokalemia, paradoxical CNS acidosis, and delayed ketone clearance.', teaching: 'Bicarb only if pH <6.9.' },
  { id: 'q-r12', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-antiplatelet', difficulty: 2, qtype: 'rapid', stem: 'Which PPI reduces clopidogrel activation and should be avoided?', options: ['Pantoprazole', 'Omeprazole', 'Rabeprazole', 'All PPIs equally'], answer: 1, explanation: 'Omeprazole (and esomeprazole) inhibit CYP2C19, which converts clopidogrel to its active metabolite. Pantoprazole/rabeprazole have minimal interaction — preferred with clopidogrel.', teaching: 'Clopidogrel + omeprazole = bad pair; use pantoprazole.' },
  { id: 'q-r13', subjectCode: 'ANAT', system: 'cardiovascular', conceptId: 'c-coronary', difficulty: 1, qtype: 'rapid', stem: 'The "widow-maker" artery is:', options: ['RCA', 'LAD', 'LCx', 'Posterior descending'], answer: 1, explanation: 'The LAD supplies the large anterior wall and septum — proximal occlusion causes extensive infarction with high mortality, hence "widow-maker".', teaching: 'LAD = widow-maker.' },
  { id: 'q-r14', subjectCode: 'MED', system: 'endocrine', conceptId: 'c-dm', difficulty: 1, qtype: 'rapid', stem: 'The most common cause of end-stage renal disease worldwide is:', options: ['Hypertensive nephrosclerosis', 'Diabetic nephropathy', 'Polycystic kidney disease', 'Chronic glomerulonephritis'], answer: 1, explanation: 'Diabetic nephropathy is the leading cause of ESRD globally (and in India); hypertension is second.', teaching: 'ESRD #1 = diabetes.' },
  { id: 'q-r15', subjectCode: 'BIOCH', system: 'cardiovascular', conceptId: 'c-troponin', difficulty: 1, qtype: 'rapid', stem: 'Troponin begins to rise after myocardial injury within:', options: ['30 minutes', '3–4 hours', '12 hours', '24 hours'], answer: 1, explanation: 'Troponin rises in 3–4 h, peaks at 24–48 h, and remains elevated 7–14 days. If onset >6 h prior with negative troponin, MI is largely excluded (repeat at 3–6 h).', teaching: 'Troponin: rise 3–4 h, peak 24–48 h, up to 7–14 d.' },
  { id: 'q-r16', subjectCode: 'CM', conceptId: 'c-vaccines', difficulty: 1, qtype: 'rapid', stem: 'Vitamin A first dose under UIP is given at:', options: ['Birth', '6 weeks', '9 months', '15 months'], answer: 2, explanation: 'Vitamin A: first dose 9 months with MR-1, then 5 doses every 6 months until 5 years (total 9 doses).', teaching: 'Vit A: 9 months, then 6-monthly till 5 y.' },
  { id: 'q-r17', subjectCode: 'OPHT', system: 'endocrine', conceptId: 'c-diabretino', difficulty: 1, qtype: 'rapid', stem: 'Treatment of choice for proliferative diabetic retinopathy:', options: ['Anti-VEGF injections', 'Panretinal photocoagulation', 'Vitrectomy as first step', 'Intravitreal steroids'], answer: 1, explanation: 'PDR → panretinal photocoagulation (ablates ischemic retina, reduces VEGF). Anti-VEGF is first-line for diabetic MACULAR EDEMA; vitrectomy for non-clearing vitreous hemorrhage/tractional detachment.', teaching: 'PDR = PRP laser; macular edema = anti-VEGF.' },
  { id: 'q-r18', subjectCode: 'OBGY', conceptId: 'c-preec', difficulty: 1, qtype: 'rapid', stem: 'Proteinuria threshold (24 h) for preeclampsia diagnosis:', options: ['150 mg', '300 mg', '500 mg', '3.5 g'], answer: 1, explanation: 'Preeclampsia: ≥300 mg/24 h (or protein:creatinine ≥0.3, or dipstick 2+). 3.5 g/day is the nephrotic threshold — a common trap pairing.', teaching: 'Preeclampsia 300 mg vs nephrotic 3.5 g.' },
  { id: 'q-r19', subjectCode: 'PHARM', system: 'cardiovascular', conceptId: 'c-betablock', difficulty: 1, qtype: 'rapid', stem: 'Beta-blocker overdose is treated with:', options: ['Naloxone', 'Glucagon', 'N-acetylcysteine', 'Flumazenil'], answer: 1, explanation: 'Glucagon bypasses the blocked β-receptor by activating adenylate cyclase directly → ↑cAMP → restored inotropy/chronotropy.', teaching: 'BB overdose → glucagon (bypasses receptor).' },
  { id: 'q-r20', subjectCode: 'SURG', conceptId: 'c-hernia', difficulty: 1, qtype: 'rapid', stem: 'The gold standard repair for inguinal hernia in adults:', options: ['Bassini repair', 'Lichtenstein tension-free mesh', 'Shouldice repair', 'Herniotomy alone'], answer: 1, explanation: 'Lichtenstein open tension-free mesh repair is the gold standard; laparoscopic (TEP/TAPP) alternatives for recurrent/bilateral. Bassini/Shouldice are tissue (suture) repairs with higher recurrence.', teaching: 'Lichtenstein mesh = gold standard.' },
  // ── INTEGRATED / VIGNETTE ──
  {
    id: 'q-int1', subjectCode: 'MED', system: 'renal', conceptId: 'c-nephrotic', difficulty: 3, qtype: 'integrated',
    stem: 'A 9-year-old with relapsing nephrotic syndrome presents with fever, abdominal guarding and rebound tenderness. Ascitic fluid shows 5000 neutrophils/µL. The most likely organism is:',
    options: ['E. coli', 'Streptococcus pneumoniae', 'Staphylococcus aureus', 'Klebsiella'],
    answer: 1,
    explanation: 'Nephrotic children lose immunoglobulins and complement factor B in urine → susceptibility to primary peritonitis with ENCAPSULATED organisms, classically S. pneumoniae. Spontaneous bacterial peritonitis in cirrhosis is typically E. coli (enteric) — the contrast is the exam trap.',
    teaching: 'Nephrotic child + peritonitis = pneumococcus; cirrhotic = E. coli.',
  },
  {
    id: 'q-int2', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-betablock', difficulty: 3, qtype: 'integrated',
    stem: 'A 58-year-old diabetic on metoprolol for post-MI protection develops sweating, tremor and confusion. Blood glucose is 52 mg/dL. The absent warning symptom was likely:',
    options: ['Sweating', 'Palpitations', 'Both', 'Neither — sweating persists with beta-blockade'],
    answer: 3,
    explanation: 'Beta-blockers block adrenergic hypoglycemia warnings — palpitations and TREMOR — but sweating (cholinergic, mediated by sympathetic cholinergic fibers) persists and remains an intact warning sign. This asymmetry is the exam point (and a clinical safety point).',
    teaching: 'BB block tremor/palpitations; SWEATING persists in hypoglycemia.',
  },
  // ── STRUGGLE ZONES (the classic "most difficult" topics) ──
  {
    id: 'q-abg1', subjectCode: 'PHYS', system: 'renal', conceptId: 'c-acidbase', difficulty: 3, qtype: 'vignette',
    stem: 'A 24-year-old salicylate overdose shows pH 7.31, pCO₂ 28 mmHg, HCO₃⁻ 14 mEq/L, Na⁺ 140, Cl⁻ 104. The primary disorder and anion gap are:',
    options: ['Respiratory alkalosis, AG 12', 'High-AG metabolic acidosis with respiratory alkalosis, AG 32', 'Metabolic alkalosis, AG 8', 'Normal ABG, AG 16'],
    answer: 1,
    explanation: 'pH 7.31 + HCO₃⁻ 14 = metabolic acidosis. AG = 140 − (104 + 14) = 32 (elevated → salicylate/lactic contribution). pCO₂ 28 is LOW, which cannot be compensation for acidosis (Winters: expected pCO₂ = 1.5×14 + 8 ≈ 29 ± 2 → 28 fits, but salicylates classically drive a primary respiratory alkalosis first). Mixed disorder recognition is the exam point: salicylate toxicity = high-AG metabolic acidosis + primary respiratory alkalosis.',
    teaching: 'Salicylates: MUDPILES + hyperventilation — always check for a mixed disorder.',
  },
  {
    id: 'q-abg2', subjectCode: 'PHYS', system: 'renal', conceptId: 'c-acidbase', difficulty: 3, qtype: 'vignette',
    stem: 'A patient with persistent vomiting shows pH 7.50, HCO₃⁻ 32, pCO₂ 42, urine chloride 12 mEq/L. The most likely cause is:',
    options: ['Acetazolamide use', 'Diarrhoea', 'Gastric outlet obstruction', 'Type 1 RTA'],
    answer: 2,
    explanation: 'Vomiting/gastric suction loses H⁺ and Cl⁻ → hypochloremic metabolic ALKALOSIS with acidic urine and LOW urine chloride (<20, saline-responsive). Diarrhoea causes normal-AG acidosis; acetazolamide causes metabolic acidosis; Type 1 RTA is acidosis with urine pH >5.5.',
    teaching: 'Vomiting → low urine Cl⁻ alkalosis (saline-responsive).',
  },
  {
    id: 'q-abg3', subjectCode: 'MED', system: 'renal', conceptId: 'c-acidbase', difficulty: 4, qtype: 'sba',
    stem: 'Metabolic acidosis with pCO₂ 20 mmHg and HCO₃⁻ 8 mEq/L. According to Winters formula, this compensation is:',
    options: ['Appropriate', 'Inappropriately low — additional respiratory alkalosis', 'Inappropriately high — additional respiratory acidosis', 'Impossible physiologically'],
    answer: 0,
    explanation: 'Expected pCO₂ = 1.5 × HCO₃⁻ + 8 ± 2 = 1.5 × 8 + 8 = 20 ± 2. The measured 20 mmHg is exactly appropriate compensation. Compensation never over-corrects — if it fell outside 18–22, you would hunt for a second (respiratory) disorder.',
    teaching: 'Winters: 1.5×HCO₃⁻ + 8 ± 2 — memorise it for every ABG vignette.',
  },
  {
    id: 'q-rta1', subjectCode: 'PHYS', system: 'renal', conceptId: 'c-rta', difficulty: 4, qtype: 'vignette',
    stem: 'A 30-year-old with recurrent calcium phosphate stones has pH 7.32, HCO₃⁻ 17, K⁺ 3.1, urine pH 6.5. The most likely diagnosis is:',
    options: ['Type 1 (distal) RTA', 'Type 2 (proximal) RTA', 'Type 4 RTA', 'Diarrhoea-related acidosis'],
    answer: 0,
    explanation: 'Distal (Type 1) RTA: the α-intercalated cells cannot secrete H⁺, so urine pH stays >5.5 despite systemic acidosis — promoting calcium phosphate stone formation. Hypokalemia is typical. Type 2 is proximal bicarbonaturia (Fanconi, growth failure, stones uncommon); Type 4 shows HYPERkalemia with urine pH <5.5; diarrhoea gives normal-AG acidosis but urine pH <5.5.',
    teaching: 'Stones + alkaline urine + hypokalemia = distal RTA.',
  },
  {
    id: 'q-coag1', subjectCode: 'PATHO', system: 'hematology', conceptId: 'c-coag', difficulty: 3, qtype: 'vignette',
    stem: 'A patient on heparin infusion has aPTT 95 s (control 32), PT 13 s (control 12), platelets fell from 220,000 to 90,000. The best next step is:',
    options: ['Continue heparin with dose reduction', 'Stop heparin, start argatroban', 'Start warfarin', 'Give protamine and continue monitoring'],
    answer: 1,
    explanation: 'A >50% platelet fall on heparin = heparin-induced thrombocytopenia (HIT) until proven otherwise — a PROTHROMBOTIC state (anti-PF4 antibodies). Stop all heparin (including flushes) and switch to a non-heparin anticoagulant (argatroban, bivalirudin, or fondaparinux). Protamine reverses bleeding, not HIT; warfarin alone early can cause venous limb gangrene.',
    teaching: 'HIT = platelets fall >50% + thrombosis risk → stop heparin, argatroban/bivalirudin.',
  },
  {
    id: 'q-coag2', subjectCode: 'PHARM', system: 'hematology', conceptId: 'c-coag', difficulty: 3, qtype: 'sba',
    stem: 'Warfarin skin necrosis occurring on day 2 of therapy is best explained by:',
    options: ['Direct endothelial toxicity', 'Early depletion of protein C before factors II, IX, X', 'Vitamin K overdose', 'Heparin contamination'],
    answer: 1,
    explanation: 'Protein C (and S) have the shortest half-lives among vitamin-K factors, so warfarin transiently lowers the anticoagulant arm FIRST — a hypercoagulable window causing microvascular thrombosis in skin fat. That is why therapeutic heparin must bridge the first 4–5 days of warfarin.',
    teaching: 'Warfarin bridge = protein C falls first (skin necrosis risk).',
  },
  {
    id: 'q-imm1', subjectCode: 'MICRO', system: 'infectious', conceptId: 'c-hypersensitivity', difficulty: 3, qtype: 'vignette',
    stem: 'A boy has recurrent skin abscesses with S. aureus and Aspergillus since childhood. DHR (dihydrorhodamine) test is abnormal. The defective mechanism is:',
    options: ['IgG class switching', 'NADPH oxidase in phagocytes', 'Terminal complement C5–C9', 'T-cell CD40 ligand'],
    answer: 1,
    explanation: 'Chronic granulomatous disease = NADPH oxidase defect → phagocytes cannot generate the respiratory burst → recurrent CATALASE-POSITIVE organisms (S. aureus, Pseudomonas, Candida, Aspergillus, Serratia). Abnormal DHR/NBT confirms it. Terminal complement deficiency causes Neisseria infections; CD40L defect is hyper-IgM with opportunistic (PCP, Cryptosporidium) infections.',
    teaching: 'Catalase-positive bugs + normal pus + abnormal DHR = CGD.',
  },
  {
    id: 'q-imm2', subjectCode: 'PATHO', conceptId: 'c-hypersensitivity', difficulty: 2, qtype: 'sba',
    stem: 'Tuberculin skin test positivity 48–72 hours after PPD inoculation is which hypersensitivity type, mediated by:',
    options: ['Type I — IgE + mast cells', 'Type II — IgG + complement', 'Type III — immune complexes', 'Type IV — CD4⁺ Th1 cells and macrophages'],
    answer: 3,
    explanation: 'The Mantoux reaction is delayed-type hypersensitivity (Type IV): antigen-presenting cells present PPD peptides to memory CD4⁺ Th1 cells, which release IFN-γ and recruit macrophages over 48–72 h — induration, not wheal. No antibody participates.',
    teaching: 'PPD at 48–72 h = Type IV, Th1-mediated.',
  },
  {
    id: 'q-gsd1', subjectCode: 'BIOCH', conceptId: 'c-glycogen', difficulty: 3, qtype: 'vignette',
    stem: 'A 4-year-old with doll-like facies and hepatomegaly has fasting hypoglycemia, lactic acidosis, hyperuricemia and hyperlipidemia. Treatment includes frequent cornstarch feeds. The enzyme deficiency is:',
    options: ['Muscle glycogen phosphorylase', 'Lysosomal α-glucosidase', 'Glucose-6-phosphatase', 'Glycogen debranching enzyme'],
    answer: 2,
    explanation: 'Von Gierke disease (Type I) = glucose-6-phosphatase deficiency: the liver cannot release free glucose from G6P → severe fasting hypoglycemia with lactic acidosis, hyperuricemia (G6P shunts to PPP/purines) and hyperlipidemia. Cornstarch provides slow-release glucose. McArdle (V) = muscle phosphorylase (exercise intolerance, no lactate rise); Pompe (II) = lysosomal α-glucosidase (cardiomegaly); Cori (III) = debrancher (milder, normal lactate).',
    teaching: 'Hypoglycemia + lactate + gout + hepatomegaly = Von Gierke (G6Pase).',
  },
  {
    id: 'q-brach1', subjectCode: 'ANAT', system: 'musculoskeletal', conceptId: 'c-brachial', difficulty: 3, qtype: 'vignette',
    stem: 'After a difficult shoulder dystocia delivery, the newborn holds the arm adducted, internally rotated with extended elbow and flexed wrist. The injured segments are:',
    options: ['C8–T1 lower trunk', 'C5–C6 upper trunk', 'T1 sympathetic chain only', 'C7 middle trunk'],
    answer: 1,
    explanation: 'Erb palsy (C5–C6, upper trunk) from lateral traction at birth produces the classic "waiter\'s tip" posture: shoulder adduction (unopposed pectoral), internal rotation (subscapularis), elbow extension (triceps), forearm pronation with wrist flexion — loss of abductors/external rotators/supinators. C8–T1 (Klumpke) gives a claw hand ± Horner syndrome.',
    teaching: 'Shoulder dystocia + waiter\'s tip = Erb (C5–C6).',
  },
  {
    id: 'q-cranial1', subjectCode: 'MED', system: 'neurology', conceptId: 'c-cranial', difficulty: 4, qtype: 'vignette',
    stem: 'A 62-year-old with sudden "down and out" right eye, ptosis, and a BLOWN pupil that does not react. The most likely cause is:',
    options: ['Diabetic ischaemic mononeuropathy', 'Posterior communicating artery aneurysm', 'Horner syndrome', 'Internuclear ophthalmoplegia'],
    answer: 1,
    explanation: 'Pupil-involved third nerve palsy = compressive lesion until proven otherwise — posterior communicating artery aneurysm (surgical emergency, needs CTA/DSA). Parasympathetic fibres run peripherally in CN III, so external compression (aneurysm, uncal herniation) hits the pupil first; ischaemic/diabetic palsies are centrally infarcted and SPARE the pupil.',
    teaching: 'Blown pupil + down-and-out = compressive CN III → aneurysm workup NOW.',
  },
  {
    id: 'q-biost1', subjectCode: 'CM', conceptId: 'c-biostat', difficulty: 3, qtype: 'sba',
    stem: 'A screening test with sensitivity 90% and specificity 95% is applied to a population with disease prevalence 1%. A positive result means the probability of disease is approximately:',
    options: ['About 90%', 'About 50%', 'About 15%', 'About 95%'],
    answer: 2,
    explanation: 'In 10,000 people: 100 diseased → 90 test positive (TP); 9,900 healthy → 495 false positives. PPV = 90/(90+495) ≈ 15%. Low prevalence makes even highly specific tests generate mostly false positives — the core argument against blanket screening (and the reason confirmatory tests need high specificity).',
    teaching: 'Low prevalence tanks PPV — sensitivity rules OUT, specificity rules IN.',
  },
  {
    id: 'q-biost2', subjectCode: 'CM', conceptId: 'c-biostat', difficulty: 2, qtype: 'sba',
    stem: 'A study compares mean birth weights across three dietary groups. The data are normally distributed. The most appropriate test is:',
    options: ['Chi-square test', 'Paired t-test', 'One-way ANOVA', 'Mann-Whitney U test'],
    answer: 2,
    explanation: 'Comparing the MEANS of ≥3 independent groups with continuous (approximately normal) data → one-way ANOVA. Chi-square handles proportions; paired t-test is for two related measurements; Mann-Whitney is the non-parametric alternative for two groups. Post-hoc tests (Tukey/Bonferroni) follow a significant ANOVA.',
    teaching: '3+ group means, normal data → ANOVA (then post-hoc).',
  },
  {
    id: 'q-anti1', subjectCode: 'FMT', conceptId: 'c-antidotes', difficulty: 2, qtype: 'vignette',
    stem: 'A farmworker presents with pinpoint pupils, bradycardia, salivation, lacrimation and fasciculations after spraying pesticide. The FIRST drug to give is:',
    options: ['Pralidoxime', 'Atropine', 'Diazepam', 'N-acetylcysteine'],
    answer: 1,
    explanation: 'Organophosphate poisoning = cholinergic crisis (SLUDGE + killer Bs). Atropine comes FIRST — titrated in doubling doses until secretions dry and chest clears (it blocks muscarinic effects). Pralidoxime reactivates acetylcholinesterase and addresses nicotinic signs (fasciculations, weakness) but must be given early, before enzyme "ageing".',
    teaching: 'OP poisoning: Atropine first (muscarinic), PAM early (nicotinic).',
  },
  {
    id: 'q-anti2', subjectCode: 'FMT', conceptId: 'c-antidotes', difficulty: 2, qtype: 'sba',
    stem: 'A snakebite patient develops ptosis, external ophthalmoplegia and respiratory weakness. The 20-minute whole blood clotting test is normal. The most appropriate treatment is:',
    options: ['Polyvalent ASV + neostigmine atropine test', 'Incision and suction at the bite site', 'Tourniquet above the bite', 'Antihistamines only'],
    answer: 0,
    explanation: 'Neurotoxic elapid envenomation without haematotoxicity (20WBCT normal) → polyvalent anti-snake venom PLUS neostigmine (with atropine to block muscarinic effects) which can reverse neurotoxic ptosis/respiratory weakness. Tourniquets and incision-suction are harmful, outdated practices.',
    teaching: 'Neurotoxic snakebite: ASV + neostigmine/atropine; never tourniquet.',
  },
  {
    id: 'q-arr1', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-arrhythmia', difficulty: 3, qtype: 'vignette',
    stem: 'A stable 28-year-old has a regular narrow-complex tachycardia at 180/min with no visible P waves. After vagal maneuvers fail, the drug of first choice is:',
    options: ['Adenosine 6 mg rapid IV push', 'Amiodarone infusion', 'Digoxin', 'Adrenaline'],
    answer: 0,
    explanation: 'Regular narrow-complex tachycardia without visible P waves = AVNRT (paroxysmal SVT). Stable patient: vagal maneuvers → adenosine 6 mg rapid push (followed by 12 mg) — its ultra-short half-life transiently blocks the AV node and often terminates the circuit. Amiodarone is for wide/VT; digoxin is slow; adrenaline worsens it.',
    teaching: 'Stable SVT: vagal → adenosine 6→12 mg.',
  },
  {
    id: 'q-arr2', subjectCode: 'MED', system: 'cardiovascular', conceptId: 'c-arrhythmia', difficulty: 4, qtype: 'sba',
    stem: 'A patient on haloperidol and ciprofloxacin develops polymorphic VT with twisting QRS axis. After stopping the drugs, the FIRST drug to give is:',
    options: ['Amiodarone', 'IV magnesium sulphate', 'Lidocaine', 'Adenosine'],
    answer: 1,
    explanation: 'Torsades de pointes = polymorphic VT with long QT (haloperidol, macrolides, quinolones, antiemetics). IV magnesium sulphate suppresses early afterdepolarizations and is first-line even with normal Mg levels. Amiodarone prolongs QT further — contraindicated. Overdrive pacing/isoprenaline are backups; unsynchronized shock if pulseless.',
    teaching: 'Twisting QRS + long QT = Torsades → IV Mg²⁺; stop QT drugs.',
  },
  {
    id: 'q-ster1', subjectCode: 'PHARM', conceptId: 'c-steroids', difficulty: 3, qtype: 'sba',
    stem: 'A nephrotic syndrome patient on prednisolone 40 mg/m² for 6 weeks develops an intercurrent fever. The correct steroid action during illness is:',
    options: ['Stop the steroid immediately', 'Continue the same dose', 'Double the oral dose (sick-day rule)', 'Switch to dexamethasone'],
    answer: 2,
    explanation: 'Chronic steroids (>3 weeks or >7.5 mg/day prednisolone equivalent) suppress the HPA axis, so physiologic stress demands supplementary cortisol — the "sick-day rule" doubles the oral dose (or switches to IV hydrocortisone if vomiting/unable to take orals). Stopping abruptly risks adrenal crisis; doubling continues until recovery.',
    teaching: 'Chronic steroid + stress = double the dose; never stop abruptly.',
  },
  {
    id: 'q-cxr1', subjectCode: 'RAD', system: 'respiratory', conceptId: 'c-cxr', difficulty: 2, qtype: 'vignette',
    stem: 'A chest X-ray shows dense opacification of the left hemithorax with the trachea and mediastinum PULSED toward the opacity and absent breath sounds. The most likely diagnosis is:',
    options: ['Massive pleural effusion', 'Total lung collapse (atelectasis)', 'Lobar pneumonia', 'Tension pneumothorax'],
    answer: 1,
    explanation: 'Mediastinal shift TOWARD the white hemithorax = volume LOSS → total lung collapse. Effusion and large mass PUSH the mediastinum AWAY; pneumonia does not shift (consolidation without volume loss); tension pneumothorax pushes away with hyperlucency, not whiteness. The CXR "white-out + shift" binary is a guaranteed exam discriminator.',
    teaching: 'White hemithorax: toward = collapse; away = effusion/mass.',
  },
  {
    id: 'q-airway1', subjectCode: 'ANES', conceptId: 'c-airway', difficulty: 3, qtype: 'vignette',
    stem: 'During induction, a patient given suxamethonium develops jaw rigidity, tachycardia, rising ETCO₂ and temperature 39°C. After stopping volatile agents, the specific treatment is:',
    options: ['IV dantrolene + active cooling', 'Nebulised salbutamol', 'IV calcium gluconate', 'Naloxone'],
    answer: 0,
    explanation: 'Malignant hyperthermia: RYR1-related uncontrolled sarcoplasmic Ca²⁺ release triggered by volatile anaesthetics and suxamethonium. Rising ETCO₂ with tachycardia/rigidity precedes fever. Management: stop triggers, call for help, dantrolene 2.5 mg/kg rapid IV (repeated to effect) + active cooling ± treat hyperkalemia. Dantrolene availability is a legal/safety requirement in every OT.',
    teaching: 'MH = sux + volatile → ETCO₂ spike → dantrolene (ryanodine blocker).',
  },
  {
    id: 'q-gen1', subjectCode: 'PEDS', conceptId: 'c-genetics', difficulty: 3, qtype: 'vignette',
    stem: 'A family tree shows affected fathers transmitting the disease to ALL daughters, no sons, and affected mothers transmitting to 50% of both sexes. The pattern is:',
    options: ['Autosomal dominant', 'X-linked dominant', 'X-linked recessive', 'Mitochondrial'],
    answer: 1,
    explanation: 'X-linked dominant: an affected father gives his only X to all daughters (all affected) and his Y to sons (none affected). AD gives father-to-son transmission; XLR never passes father→son and daughters are carriers; mitochondrial is maternal-only to all offspring.',
    teaching: 'All daughters, no sons from affected father = X-linked dominant.',
  },
  {
    id: 'q-fluids1', subjectCode: 'PEDS', conceptId: 'c-fluids', difficulty: 2, qtype: 'vignette',
    stem: 'A 10-kg infant with acute watery diarrhoea is restless, has sunken eyes and a skin pinch that retracts in 2 seconds. Heart rate is elevated with palpable pulses. WHO classification and plan are:',
    options: ['No dehydration — Plan A', 'Some dehydration — Plan B', 'Severe dehydration — Plan C', 'Shock — immediate 40 ml/kg bolus'],
    answer: 1,
    explanation: 'Restlessness/irritability, sunken eyes and a skin pinch returning in <2 s (some, not slow ≥2 s) with palpable pulses = "SOME" dehydration (6–9%) → WHO Plan B: 75 ml/kg ORS over 4 hours, then reassess. Severe dehydration (lethargy, slow ≥2 s pinch, absent pulses) needs Plan C IV fluids: 30 ml/kg in the first hour for infants.',
    teaching: 'Pinch <2 s + restless = Plan B (75 ml/kg ORS/4 h).',
  },
]

export const flashcards: SeedFlashcard[] = [
  { id: 'f-1', conceptId: 'c-nephrotic', subjectCode: 'PATHO', system: 'renal', front: 'Diagnostic triad of nephrotic syndrome?', back: 'Proteinuria >3.5 g/day + hypoalbuminemia (<2.5–3) + edema; ± hyperlipidemia/lipiduria.' },
  { id: 'f-2', conceptId: 'c-nephrotic', subjectCode: 'PATHO', system: 'renal', front: 'Most common nephrotic cause in children 2–12 y?', back: 'Minimal change disease — steroid-responsive; foot process effacement on EM.' },
  { id: 'f-3', conceptId: 'c-nephrotic', subjectCode: 'PATHO', system: 'renal', front: 'Why renal vein thrombosis in nephrotic syndrome?', back: 'Urinary loss of antithrombin III (+ proteins C/S) → hypercoagulability.' },
  { id: 'f-4', conceptId: 'c-nephritic', subjectCode: 'PATHO', system: 'renal', front: 'Nephritic pentad?', back: 'Hematuria (RBC casts) + hypertension + oliguria + mild proteinuria + ↓GFR.' },
  { id: 'f-5', conceptId: 'c-nephritic', subjectCode: 'PATHO', system: 'renal', front: 'IF pattern: linear IgG / granular / pauci-immune?', back: 'Linear = anti-GBM (Goodpasture); granular = immune complex (strep, lupus, IgA); none = ANCA (GPA, MPA).' },
  { id: 'f-6', conceptId: 'c-nephritic', subjectCode: 'PATHO', system: 'renal', front: 'IgA nephropathy timing vs post-strep GN?', back: 'IgA: 1–2 days after URTI (synpharyngitic). Post-strep: 1–3 weeks after pharyngitis/impetigo with low C3.' },
  { id: 'f-7', conceptId: 'c-raas', subjectCode: 'PHYS', system: 'renal', front: 'Three renin triggers?', back: '↓Perfusion pressure (baroreceptor), ↓NaCl at macula densa, β1 sympathetic stimulation.' },
  { id: 'f-8', conceptId: 'c-raas', subjectCode: 'PHYS', system: 'renal', front: 'Four actions of angiotensin II?', back: 'Vasoconstriction (AT1), aldosterone release, ADH+thirst, potentiate sympathetic; also remodeling.' },
  { id: 'f-9', conceptId: 'c-acei', subjectCode: 'PHARM', system: 'cardiovascular', front: 'ACEi top 4 indications with outcome benefit?', back: 'Post-MI remodeling, HFrEF mortality, diabetic nephropathy (albuminuria), hypertension.' },
  { id: 'f-10', conceptId: 'c-acei', subjectCode: 'PHARM', system: 'cardiovascular', front: 'ACEi cough/angioedema mechanism?', back: 'Bradykinin accumulation (ACE degrades bradykinin); switch to ARB.' },
  { id: 'f-11', conceptId: 'c-betablock', subjectCode: 'PHARM', system: 'cardiovascular', front: 'Cardioselective beta-blockers?', back: 'Metoprolol, atenolol, bisoprolol, nebivolol (β1 selective — safer in asthma, still caution).' },
  { id: 'f-12', conceptId: 'c-betablock', subjectCode: 'PHARM', system: 'cardiovascular', front: 'Beta-blocker withdrawal syndrome?', back: 'Rebound tachycardia/angina/MI from receptor upregulation — always taper.' },
  { id: 'f-13', conceptId: 'c-betablock', subjectCode: 'PHARM', system: 'cardiovascular', front: 'Which beta-blockers reduce mortality in HFrEF?', back: 'Bisoprolol, carvedilol, metoprolol succinate (start low-go slow once euvolemic).' },
  { id: 'f-14', conceptId: 'c-cardcycle', subjectCode: 'PHYS', system: 'cardiovascular', front: 'S1 vs S2 vs S3 vs S4 timing?', back: 'S1: AV closure (start systole). S2: semilunar closure (start IVR). S3: rapid filling (volume overload). S4: atrial kick vs stiff ventricle.' },
  { id: 'f-15', conceptId: 'c-cardcycle', subjectCode: 'PHYS', system: 'cardiovascular', front: 'Order the 7 cardiac cycle phases?', back: 'Atrial systole → IVC → rapid ejection → reduced ejection → IVR → rapid filling → diastasis.' },
  { id: 'f-16', conceptId: 'c-coronary', subjectCode: 'ANAT', system: 'cardiovascular', front: 'ECG territories: LAD / RCA / LCx?', back: 'LAD: V1–V4 (anteroseptal). RCA: II, III, aVF (inferior). LCx: I, aVL, V5–V6 (lateral).' },
  { id: 'f-17', conceptId: 'c-ami', subjectCode: 'MED', system: 'cardiovascular', front: 'Troponin timeline?', back: 'Rise 3–4 h → peak 24–48 h → elevated 7–14 days. CK-MB normalizes 48–72 h (reinfarction marker).' },
  { id: 'f-18', conceptId: 'c-ami', subjectCode: 'MED', system: 'cardiovascular', front: 'Post-MI complications timeline?', back: 'Arrhythmia <24 h. Papillary/septal rupture 3–7 d. Free wall rupture 5–10 d (tamponade). Aneurysm + Dressler weeks (persistent ST elevation).' },
  { id: 'f-19', conceptId: 'c-ami', subjectCode: 'MED', system: 'cardiovascular', front: 'Door-to-balloon vs door-to-needle?', back: 'PCI ≤90 min (transfer ≤120); fibrinolysis ≤30 min.' },
  { id: 'f-20', conceptId: 'c-ecg', subjectCode: 'MED', system: 'cardiovascular', front: 'Hyperkalemia ECG progression?', back: 'Peaked T → P flattening → QRS widening → sine wave.' },
  { id: 'f-21', conceptId: 'c-ecg', subjectCode: 'MED', system: 'cardiovascular', front: 'Pericarditis vs STEMI on ECG?', back: 'Pericarditis: diffuse concave ST elevation + PR depression, no reciprocals. STEMI: territorial + reciprocal depression.' },
  { id: 'f-22', conceptId: 'c-antiplatelet', subjectCode: 'PHARM', system: 'cardiovascular', front: 'Antiplatelet targets in order of pathway?', back: 'COX-1 (aspirin) → P2Y12/ADP (clopidogrel, ticagrelor) → GPIIb/IIIa (abciximab) — final common pathway.' },
  { id: 'f-23', conceptId: 'c-htn', subjectCode: 'MED', system: 'cardiovascular', front: 'HTN + unprovoked hypokalemia?', back: 'Think primary aldosteronism → plasma aldosterone:renin ratio.' },
  { id: 'f-24', conceptId: 'c-htn', subjectCode: 'MED', system: 'cardiovascular', front: 'Hypertensive emergency definition?', back: 'Severe BP + ACUTE target-organ damage → IV therapy (labetalol, nicardipine). No damage = urgency, oral titration.' },
  { id: 'f-25', conceptId: 'c-htn', subjectCode: 'OBGY', front: 'Safe antihypertensives in pregnancy?', back: 'Labetalol, methyldopa, nifedipine. NEVER ACEi/ARB (fetal renal failure).' },
  { id: 'f-26', conceptId: 'c-gfr', subjectCode: 'PHYS', system: 'renal', front: 'NSAID vs ACEi on the nephron?', back: 'NSAID: afferent constriction (↓PG). ACEi: efferent dilation. Together: GFR collapse (double hit).' },
  { id: 'f-27', conceptId: 'c-aki', subjectCode: 'MED', system: 'renal', front: 'Prerenal vs ATN indices?', back: 'Prerenal: FENa <1%, BUN:Cr >20:1, urine Na <20. ATN: FENa >2%, BUN:Cr ~10–15:1, muddy brown casts.' },
  { id: 'f-28', conceptId: 'c-aki', subjectCode: 'MED', system: 'renal', front: 'Dialysis indications — AEIOU?', back: 'Acidosis, Electrolyte (refractory hyperK), Intoxication, Overload (fluid), Uremia.' },
  { id: 'f-29', conceptId: 'c-hyperk', subjectCode: 'MED', system: 'renal', front: 'Hyperkalemia 3-step management?', back: 'Stabilize (IV calcium) → Shift (insulin+glucose, salbutamol, bicarb) → Remove (binder, dialysis).' },
  { id: 'f-30', conceptId: 'c-diuretics', subjectCode: 'PHARM', system: 'renal', front: 'Loop diuretic electrolyte signature?', back: 'Hypo-K, hypo-Mg, hypo-Ca, metabolic ALKALOSIS, ototoxicity.' },
  { id: 'f-31', conceptId: 'c-diuretics', subjectCode: 'PHARM', system: 'renal', front: 'Thiazide electrolyte signature?', back: 'Hypo-K, hypo-Na, hyper-Ca (keep), hyperuricemia, hyperglycemia, metabolic alkalosis.' },
  { id: 'f-32', conceptId: 'c-diuretics', subjectCode: 'PHARM', system: 'renal', front: 'Spironolactone vs eplerenone?', back: 'Spironolactone also blocks androgen/progesterone → gynecomastia. Eplerenone selective MRA — no gynecomastia.' },
  { id: 'f-33', conceptId: 'c-insulin', subjectCode: 'PHYS', system: 'endocrine', front: 'Insulin and potassium?', back: 'Insulin ↑Na/K-ATPase → K⁺ into cells → basis of insulin-dextrose in hyperkalemia.' },
  { id: 'f-34', conceptId: 'c-dm', subjectCode: 'MED', system: 'endocrine', front: 'Diagnostic thresholds for DM?', back: 'FPG ≥126 / OGTT 2h ≥200 / HbA1c ≥6.5% / random ≥200 + symptoms.' },
  { id: 'f-35', conceptId: 'c-dm', subjectCode: 'MED', system: 'endocrine', front: 'T1 vs T2 markers?', back: 'T1: GAD/IA-2 antibodies, ketosis-prone, young. T2: insulin resistance, metabolic syndrome, strong family history.' },
  { id: 'f-36', conceptId: 'c-dka', subjectCode: 'MED', system: 'endocrine', front: 'DKA management sequence?', back: 'Fluids (isotonic saline) → insulin infusion → K⁺ once <5.2 & urine flows → dextrose when glucose <250 → bicarb only pH <6.9.' },
  { id: 'f-37', conceptId: 'c-dka', subjectCode: 'MED', system: 'endocrine', front: 'Serum K in DKA is misleading — why?', back: 'Acidosis + insulin lack shift K⁺ OUT of cells; total-body K⁺ is depleted. Insulin will drop serum K fast.' },
  { id: 'f-38', conceptId: 'c-metformin', subjectCode: 'PHARM', system: 'endocrine', front: 'Metformin: mechanism + main caution?', back: 'AMPK activation → ↓hepatic gluconeogenesis. Contraindicated eGFR <30 (lactic acidosis); B12 deficiency long-term.' },
  { id: 'f-39', conceptId: 'c-thyroidphys', subjectCode: 'PHYS', system: 'endocrine', front: 'Wolff-Chaikoff vs Jod-Basedow?', back: 'W-C: iodine load transiently INHIBITS synthesis (therapeutic in storm). J-B: iodine triggers hyperthyroidism in autonomous nodules.' },
  { id: 'f-40', conceptId: 'c-graves', subjectCode: 'MED', system: 'endocrine', front: 'Graves vs TMNG vs thyroiditis on uptake scan?', back: 'Graves: diffuse ↑uptake. TMNG: patchy hot nodules. Thyroiditis/exogenous: near-zero uptake.' },
  { id: 'f-41', conceptId: 'c-thyroidstorm', subjectCode: 'MED', system: 'endocrine', front: 'Thyroid storm — 5 blocks in order?', back: 'β-blocker → PTU (block synthesis) → iodine 1 h later → steroids → supportive.' },
  { id: 'f-42', conceptId: 'c-cushing', subjectCode: 'MED', system: 'endocrine', front: 'Cushing: high-dose dex suppression pattern?', back: 'Pituitary adenoma suppresses; ectopic ACTH does not; adrenal adenoma has low ACTH.' },
  { id: 'f-43', conceptId: 'c-spirometry', subjectCode: 'PHYS', system: 'respiratory', front: 'Obstructive vs restrictive spirometry?', back: 'Obstructive: FEV1/FVC <0.7. Restrictive: ratio normal/↑ with ↓FVC (↓TLC).' },
  { id: 'f-44', conceptId: 'c-spirometry', subjectCode: 'PHYS', system: 'respiratory', front: 'DLCO patterns?', back: '↓: emphysema, IPF. ↑: asthma, pulmonary hemorrhage, obesity(mild).' },
  { id: 'f-45', conceptId: 'c-asthma-copd', subjectCode: 'MED', system: 'respiratory', front: 'Asthma step-up ladder (GINA)?', back: 'SABA PRN → low-dose ICS → ICS+LABA → high-dose ICS+LABA → add-ons (tiotropium, omalizumab).' },
  { id: 'f-46', conceptId: 'c-asthma-copd', subjectCode: 'MED', system: 'respiratory', front: 'The asthma mortality rule?', back: 'Never LABA monotherapy — always with ICS.' },
  { id: 'f-47', conceptId: 'c-tb', subjectCode: 'MICRO', system: 'respiratory', front: 'ATT toxicity matching?', back: 'INH: neuropathy (B6). Rifampin: orange + enzyme inducer. PZA: hyperuricemia. Ethambutol: red-green color loss. Streptomycin: ototoxicity.' },
  { id: 'f-48', conceptId: 'c-tb', subjectCode: 'MICRO', system: 'respiratory', front: 'NTEP first-line diagnostic?', back: 'CBNAAT/GeneXpert (2 h, detects rifampin resistance).' },
  { id: 'f-49', conceptId: 'c-antitb', subjectCode: 'MICRO', system: 'respiratory', front: 'TB meningitis regimen length?', back: '12 months + corticosteroids.' },
  { id: 'f-50', conceptId: 'c-idacda', subjectCode: 'PATHO', system: 'hematology', front: 'IDA vs ACD ferritin/TIBC?', back: 'IDA: ↓ferritin, ↑TIBC. ACD: ↑/normal ferritin, ↓TIBC (ferritin is an acute-phase reactant).' },
  { id: 'f-51', conceptId: 'c-idacda', subjectCode: 'PATHO', system: 'hematology', front: 'Mentzer index?', back: 'MCV/RBC <13 = thalassemia trait; >13 = iron deficiency.' },
  { id: 'f-52', conceptId: 'c-leukemia', subjectCode: 'PATHO', system: 'hematology', front: 'Auer rods mean?', back: 'AML (esp. M3 APL) — t(15;17) → ATRA + arsenic; watch DIC.' },
  { id: 'f-53', conceptId: 'c-leukemia', subjectCode: 'PATHO', system: 'hematology', front: 'ALL vs AML quick markers?', back: 'ALL: kids, PAS+, TdT+, CD10. AML: adults, Auer rods, MPO+.' },
  { id: 'f-54', conceptId: 'c-hpylori', subjectCode: 'MICRO', system: 'gastrointestinal', front: 'H. pylori eradication confirmation?', back: 'Urea breath test or stool antigen ≥4 wks post-antibiotics, 2 wks off PPI. NEVER serology.' },
  { id: 'f-55', conceptId: 'c-ulcer', subjectCode: 'MED', system: 'gastrointestinal', front: 'Gastric vs duodenal ulcer rule?', back: 'Gastric: worse with food, biopsy ALWAYS. Duodenal: relieved by food, H. pylori 90%.' },
  { id: 'f-56', conceptId: 'c-epidesign', subjectCode: 'CM', front: 'Odds ratio vs relative risk — which design?', back: 'Case-control → OR. Cohort/RCT → RR. OR approximates RR only in rare diseases.' },
  { id: 'f-57', conceptId: 'c-epidesign', subjectCode: 'CM', front: 'Effect of prevalence on PPV/NPV?', back: '↑Prevalence → ↑PPV, ↓NPV. Sensitivity/specificity unchanged (test properties).' },
  { id: 'f-58', conceptId: 'c-vaccines', subjectCode: 'CM', front: 'Live vaccines in UIP?', back: 'BCG, OPV, MR/MMR, JE (SA-14-14-2), varicella. Killed: DPT, HepB, IPV, Hib.' },
  { id: 'f-59', conceptId: 'c-femoral', subjectCode: 'ANAT', front: 'Femoral triangle contents lateral→medial?', back: 'NAVEL: Nerve, Artery, Vein, Empty/Lymphatics. Nerve outside femoral sheath.' },
  { id: 'f-60', conceptId: 'c-hernia', subjectCode: 'SURG', front: 'Indirect vs direct hernia landmark?', back: 'Inferior epigastric vessels: indirect lateral (via deep ring), direct medial (Hesselbach triangle).' },
  { id: 'f-61', conceptId: 'c-preec', subjectCode: 'OBGY', front: 'Eclampsia drug + antidote?', back: 'MgSO4 (Pritchard) ↔ calcium gluconate. Monitor: reflexes, respiration, urine output.' },
  { id: 'f-62', conceptId: 'c-diabretino', subjectCode: 'OPHT', front: 'Earliest diabetic retinopathy lesion?', back: 'Microaneurysms. Neovascularization = PDR → panretinal photocoagulation.' },
  { id: 'f-63', conceptId: 'c-inflamm', subjectCode: 'PATHO', front: 'Rate-limiting mediator of acute inflammation?', back: 'Histamine (vasodilation + permeability) from mast cells; complement C3a/C5a, bradykinin follow.' },
  { id: 'f-64', conceptId: 'c-neoplasia', subjectCode: 'PATHO', front: 'Tumor marker pairings?', back: 'AFP-HCC, CEA-colon, CA-125-ovary, PSA-prostate, β-hCG-chorio/germ cell.' },
  // ── Struggle-zone flashcards ──
  { id: 'f-65', conceptId: 'c-acidbase', subjectCode: 'PHYS', system: 'renal', front: 'The 5-step ABG interpretation walk?', back: 'pH → primary disorder (ROME) → compensation (Winters 1.5×HCO₃⁻+8±2) → anion gap (MUDPILES) → delta-delta for mixed disorders.' },
  { id: 'f-66', conceptId: 'c-acidbase', subjectCode: 'PHYS', system: 'renal', front: 'Vomiting vs diarrhoea acid-base signature?', back: 'Vomiting: hypochloremic hypokalemic metabolic ALKALOSIS (urine Cl⁻ <20). Diarrhoea: normal-AG hyperchloremic metabolic ACIDOSIS.' },
  { id: 'f-67', conceptId: 'c-rta', subjectCode: 'PHYS', system: 'renal', front: 'Type 1 vs 2 vs 4 RTA discriminators?', back: 'Type 1 distal: urine pH >5.5 + stones + hypoK. Type 2 proximal: Fanconi + growth failure. Type 4: HYPERkalemia + hypoaldosteronism (commonest).' },
  { id: 'f-68', conceptId: 'c-coag', subjectCode: 'PATHO', system: 'hematology', front: 'PT vs aPTT pathways?', back: 'PT/INR = extrinsic (factor VII, TF). aPTT = intrinsic (XII, XI, IX, VIII). Both prolonged = common path / liver failure / DIC.' },
  { id: 'f-69', conceptId: 'c-coag', subjectCode: 'PHARM', system: 'hematology', front: 'HIT criteria and action?', back: 'Platelet fall >50% (or thrombosis) 5–10 days after heparin → STOP heparin → argatroban/bivalirudin/fondaparinux. Never just add warfarin.' },
  { id: 'f-70', conceptId: 'c-hypersensitivity', subjectCode: 'MICRO', front: 'ACID types of hypersensitivity?', back: 'Allergy (I, IgE), Cytotoxic (II, IgG/IgM), Immune-complex (III, complement), Delayed (IV, Th1/Tc).' },
  { id: 'f-71', conceptId: 'c-hypersensitivity', subjectCode: 'PATHO', front: 'Infection fingerprint → immunodeficiency?', back: 'Encapsulated → asplenia/CVID/C3. Neisseria → C5-9. Catalase-positive → CGD. Viral/fungal/PCP → T-cell (DiGeorge, SCID).' },
  { id: 'f-72', conceptId: 'c-glycogen', subjectCode: 'BIOCH', front: 'Von Gierke vs McArdle vs Pompe?', back: 'Von Gierke (I): G6Pase — fasting hypoglycemia + lactate + gout. McArdle (V): muscle phosphorylase — cramps, NO lactate rise. Pompe (II): lysosomal α-glucosidase — infant cardiomegaly.' },
  { id: 'f-73', conceptId: 'c-brachial', subjectCode: 'ANAT', system: 'musculoskeletal', front: 'Erb vs Klumpke palsy?', back: 'Erb: C5-C6 upper trunk (shoulder dystocia) — waiter-tip. Klumpke: C8-T1 lower trunk (upward traction) — claw hand ± Horner.' },
  { id: 'f-74', conceptId: 'c-cranial', subjectCode: 'MED', system: 'neurology', front: 'CN III palsy: pupil involved vs spared?', back: 'Involved (blown) = compressive (PCom aneurysm, herniation) — surgical. Spared = ischaemic/diabetic — medical.' },
  { id: 'f-75', conceptId: 'c-biostat', subjectCode: 'CM', front: 'SPin vs SNout?', back: 'High Specificity + Positive test rules IN. High Sensitivity + Negative test rules OUT. PPV falls as prevalence falls.' },
  { id: 'f-76', conceptId: 'c-biostat', subjectCode: 'CM', front: 'Test selection: 2 means / 3+ means / 2 proportions?', back: 'Unpaired t-test / ANOVA / chi-square (Fisher if n<5). Non-parametric: Mann-Whitney, Kruskal-Wallis.' },
  { id: 'f-77', conceptId: 'c-antidotes', subjectCode: 'FMT', front: 'Antidote quick pairs?', back: 'OP → atropine+PAM. Paracetamol → NAC. Opioid → naloxone. Benzo → flumazenil. Methanol → fomepizole. Iron → deferoxamine. TCA wide QRS → NaHCO₃.' },
  { id: 'f-78', conceptId: 'c-arrhythmia', subjectCode: 'MED', system: 'cardiovascular', front: 'The 2×2 rhythm grid?', back: 'Narrow-regular: SVT/flutter. Narrow-irregular: AF/MAT. Wide-regular: VT until proven otherwise. Wide-irregular: AF with aberrancy/torsades.' },
  { id: 'f-79', conceptId: 'c-steroids', subjectCode: 'PHARM', front: 'Glucocorticoid potency ladder?', back: 'Hydrocortisone 1 → prednisolone 4 → methylpred 5 → dexamethasone 25–30 (zero mineralo). Sick-day: double the dose.' },
  { id: 'f-80', conceptId: 'c-cxr', subjectCode: 'RAD', system: 'respiratory', front: 'White hemithorax: shift toward vs away?', back: 'TOWARD opacity = volume loss (collapse). AWAY = effusion/mass. Silhouette sign localises the lobe.' },
  { id: 'f-81', conceptId: 'c-airway', subjectCode: 'ANES', front: 'Suxamethonium contraindications?', back: 'Hyperkalemia states (burns/crush >48 h), MH history, neuromuscular disease, raised IOP; MH trigger — dantrolene rescues.' },
  { id: 'f-82', conceptId: 'c-genetics', subjectCode: 'PEDS', front: 'Pedigree quick rules?', back: 'Male-to-male = AD. Skipped generations + consanguinity = AR. No father-to-son = X-linked. Mothers-only = mitochondrial.' },
  { id: 'f-83', conceptId: 'c-fluids', subjectCode: 'PEDS', front: 'WHO dehydration plans?', back: 'Some (6–9%): Plan B — 75 ml/kg ORS over 4 h. Severe (≥10%): Plan C — 30 ml/kg IV in 1 h (infants) + 70 over 2.5 h.' },
]

export const confusions: SeedConfusion[] = [
  {
    id: 'cf-1', a: 'Nephritic syndrome', b: 'Nephrotic syndrome', aCode: 'c-nephritic', bCode: 'c-nephrotic', subjectCode: 'PATHO', system: 'renal',
    aPoints: ['Hematuria with RBC casts', 'Hypertension', 'Oliguria, ↓GFR', 'Mild-moderate proteinuria (<3.5 g)', 'Active (inflammatory) sediment'],
    bPoints: ['Heavy proteinuria >3.5 g/day', 'Hypoalbuminemia <2.5–3 g/dL', 'Edema (periorbital → anasarca)', 'Hyperlipidemia + lipiduria', 'Bland sediment'],
    mnemonic: 'NEPHRITIC = INflamed (blood in urine). NEPHROTIC = leaked Out (protein out).',
  },
  {
    id: 'cf-2', a: 'Cushing disease', b: 'Cushing syndrome', aCode: 'c-cushing', subjectCode: 'MED', system: 'endocrine',
    aPoints: ['Pituitary corticotroph adenoma', 'ACTH HIGH', 'Suppresses with high-dose dexamethasone', 'Most common endogenous cause'],
    bPoints: ['Any cause of cortisol excess', 'Ectopic ACTH (no suppression) / adrenal tumor (ACTH low) / exogenous steroids', 'Exogenous steroids = most common overall'],
    mnemonic: 'Disease = Destination (pituitary). Syndrome = the whole set of features.',
  },
  {
    id: 'cf-3', a: 'Type 1 DM', b: 'Type 2 DM', aCode: 'c-dm', subjectCode: 'MED', system: 'endocrine',
    aPoints: ['Autoimmune β-cell destruction', 'Absolute insulin deficiency', 'Ketosis-prone', 'GAD-65/IA-2 antibodies', 'Young, lean, rapid onset'],
    bPoints: ['Insulin resistance + relative deficiency', 'Progressive β-cell failure', 'Ketosis rare (HHS instead)', 'Metabolic syndrome', 'Older (now younger), obese, strong heredity'],
    mnemonic: 'T1 = Total insulin lack. T2 = Tone (resistance) down.',
  },
  {
    id: 'cf-4', a: 'UMN lesion', b: 'LMN lesion', subjectCode: 'MED', system: 'neurology',
    aPoints: ['Spastic paralysis', 'Hyperreflexia', 'Babinski positive (extensor plantar)', 'No fasciculations', 'Clasp-knife spasticity', 'No/mild atrophy (disuse)'],
    bPoints: ['Flaccid paralysis', 'Hyporeflexia/areflexia', 'Fasciculations + fibrillations', 'Marked atrophy', 'Hypotonia'],
    mnemonic: 'UMN = Up (reflexes, tone). LMN = Low (everything drops: tone, reflexes, bulk).',
  },
  {
    id: 'cf-5', a: 'SIADH', b: 'Cerebral salt wasting', subjectCode: 'MED', system: 'neurology',
    aPoints: ['Euvolemic hyponatremia', 'Urine Na variable/normal', 'No dehydration signs', 'Fluid RESTRICTION first-line'],
    bPoints: ['Hypovolemic hyponatremia', 'Urine Na HIGH (>50)', 'Dehydration + weight loss', 'Needs NORMAL SALINE + salt (restriction worsens)'],
    mnemonic: 'CSW = Salt Comes out With volume; treat with Saline. SIADH = Sequester (restrict) fluids.',
  },
  {
    id: 'cf-6', a: 'Crohn disease', b: 'Ulcerative colitis', subjectCode: 'MED', system: 'gastrointestinal',
    aPoints: ['Skip lesions (patchy)', 'Transmural', 'Any part mouth→anus (terminal ileum classic)', 'Non-caseating granulomas', 'Fistulas, strictures', 'Smoking worsens'],
    bPoints: ['Continuous, starts at rectum', 'Mucosa/submucosa only', 'Colon only', 'Crypt abscesses, pseudopolyps', 'Primary sclerosing cholangitis link', 'Smoking protective (paradox)'],
    mnemonic: 'Crohn = Cobblestones + Creeps (skip) + Coral (granuloma). UC = Uniform + Up from rectum.',
  },
  // ── Struggle-zone confusion pairs ──
  {
    id: 'cf-7', a: 'Type 1 (distal) RTA', b: 'Type 2 (proximal) RTA', aCode: 'c-rta', bCode: 'c-rta', subjectCode: 'PHYS', system: 'renal',
    aPoints: ['Cannot SECRETE H⁺ (α-intercalated cells)', 'Urine pH permanently >5.5', 'Calcium PHOSPHATE stones', 'Nephrocalcinosis, rickets less prominent', 'Associated: Sjögren, SLE, amphotericin B'],
    bPoints: ['Cannot REABSORB HCO₃⁻ (proximal tubule)', 'Urine pH variable — <5.5 once plasma HCO₃⁻ falls below threshold', 'Fanconi: glucosuria, aminoaciduria, phosphaturia', 'Growth failure + hypokalemia prominent', 'Associated: carbonic anhydrase inhibitors, Wilson, cystinosis'],
    mnemonic: 'Type 1 = one stubborn alkaline urine (stones). Type 2 = two-way leak (everything reabsorbed in the proximal tubule leaks out).',
  },
  {
    id: 'cf-8', a: 'VT (ventricular tachycardia)', b: 'SVT with aberrancy', aCode: 'c-arrhythmia', bCode: 'c-arrhythmia', subjectCode: 'MED', system: 'cardiovascular',
    aPoints: ['Wide regular tachycardia — assume VT first', 'Fusion or capture beats (pathognomonic)', 'AV dissociation', 'Concordance of QRS in precordial leads', 'Prior MI/structural heart disease history'],
    bPoints: ['Wide complex with typical BBB pattern (rSR\u2019 in V1 or narrow-but-prolonged)', 'Pre-existing bundle branch block or rate-related', 'P waves identifiable in some leads', 'Responds to adenosine (diagnostic-therapeutic)', 'Young, structurally normal heart'],
    mnemonic: 'Wide + regular + history of MI = VT. Fusion/capture beats seal the diagnosis — never mis-treat VT as SVT.',
  },
  {
    id: 'cf-9', a: 'Extrinsic pathway (PT/INR)', b: 'Intrinsic pathway (aPTT)', aCode: 'c-coag', bCode: 'c-coag', subjectCode: 'PATHO', system: 'hematology',
    aPoints: ['Tissue factor + factor VII', 'Monitored for WARFARIN (INR target 2–3)', 'Prolonged early in liver disease', 'VII has the shortest half-life'],
    bPoints: ['XII → XI → IX → VIII (contact activation)', 'Monitored for HEPARIN', 'Prolonged in haemophilia A/B, vWD, lupus anticoagulant', 'VIII/IX deficiencies = aPTT-only prolongation'],
    mnemonic: 'Play Outside Then Inside: PT = Tissue factor (outside); aPTT = Intrinsic (inside the vessel wall). Warfarin-PT, Heparin-aPTT.',
  },
  {
    id: 'cf-10', a: 'Sensitivity', b: 'Specificity', aCode: 'c-biostat', bCode: 'c-biostat', subjectCode: 'CM',
    aPoints: ['True positives ÷ all diseased', 'High Sn → NEGATIVE test rules OUT (SnNout)', 'Screening tests prioritise sensitivity', 'Affected by disease prevalence only via PPV, not the metric itself'],
    bPoints: ['True negatives ÷ all healthy', 'High Sp → POSITIVE test rules IN (SPin)', 'Confirmatory tests prioritise specificity', 'Low prevalence → even high specificity yields many false positives'],
    mnemonic: 'SnNout — sensitive test, Negative rules out. SPin — specific test, Positive rules in.',
  },
]
